# -*- coding: utf-8 -*-
LEADS = [
  dict(
    slug="moose-garage-doors", name="Moose Garage Doors", name_url="Moose%20Garage%20Doors",
    city="Brampton", phone="647-368-9053", phone_tel="6473689053", wa_tel="16473689053",
    email="info@moosegaragedoors.com", rating="5.0", reviews="126", years="Est. 2026", years_label="Founded",
    logo="MG", niche_label="Garage Door Company", schema_type="HomeAndConstructionBusiness",
    services_h2="Garage door work, done right the first time",
    hero_headline="126 five-star reviews. Zero replies from us, until now.",
    tagline="Residential and commercial garage door installation, repair, and opener service across Brampton, backed by a 2-year workmanship warranty on every new door.",
    about="Moose Garage Doors was founded by Gurtej Singh after four years in manufacturing, built on honest pricing and no upselling unnecessary repairs. Customers keep naming technician Gurvir specifically for fast, reliable spring, cable, and opener repairs.",
    services=[("Garage Door Installation","Full installation of new residential and commercial garage doors."),
              ("Garage Door Repair","Fast fixes for broken springs, snapped cables, and worn rollers."),
              ("Commercial Overhead Doors","Heavy-duty overhead door installs for warehouses and shops."),
              ("Garage Door Openers","Installation and replacement of modern, quiet opener systems."),
              ("Emergency Repair","Same-day response when a door won't open or close safely."),
              ("Free Quotes","A clear, honest price before any work begins.")],
    testimonials=[("Huge shout-out to Gurvir for saving the day with my garage door! He's a total pro who actually cares about doing the job right—super fast, friendly, and honestly just a great guy to work with. Highly recommend!","Akashdeep Singh","AS"),
                  ("My garage door cables got snapped, and Gurvir from Moose Garage Door was a lifesaver. He arrived quickly, fixed the issue professionally, and got everything working perfectly again. Highly recommend his service!","Abhishek Digpal","AD"),
                  ("Satisfied with the overall service. Gurvir fixed my garage door and replaced the parts promptly. Would recommend his services with any repairs related to garage doors since he is extremely reliable and does the job well.","Harshavardhan Buchake","HB")],
    gallery_captions=["Recent garage door install","Spring & cable repair","Opener installation","Brampton service call"],
    primary="#1e3a4a", primary_dark="#132530", accent="#c9762f",
    hook="Five different customers named Gurvir by name in the last three weeks alone, and every single one of those reviews is still sitting there with zero reply. That's a lot of goodwill going unused.",
    faqs=[("Do you offer emergency garage door repair?","Yes, we respond quickly when a door won't open or close safely."),
          ("Do new doors come with a warranty?","Yes, every new garage door installed comes with a 2-year workmanship warranty, regardless of the door manufacturer."),
          ("Do you provide free quotes?","Yes, we give a clear, honest price before any work begins, no pressure."),
          ("What areas do you serve?","We serve Brampton and the surrounding GTA for residential and commercial garage door work.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnkquB6q5e2OnZ67uc6CrHuYO-T40ZJXD7Qj4GzZZFoKRccrQXawc938HFmne0L6GbvBmWeBXgPOxhjl1YiGd6861aIzTOEFG6NF74ZYv9h7acFVFQxrTubO9I5RIobovAgWCee8EuGisvN=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlGVMA5VMSF0oTeK0sTLbtHVd6PgZQsKbeNjjp9kUgqTDcRVcfBuEfdJo4JkIDKF3SsvtjLGZZ6PR1wNFCZZMgb4N5qP8tZ1mCgdwFnaCp-Yz0jR-y_aY_TCERauitqcOXI3Ovh30LY6RWU=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn0Tbbymr3IJr0IcoB84isZdx_Ao5J3asSSl7KKhvm1SlWjnt9h9lJvGQDK8x5uKmFmecJ6zdQs5dkj0MRGxntSO5hLuIpuy70IrkiCtnLq5_4O_igZ4NJuJIC1GOJJLr-UgYPk9_jNKO4z=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnjcKja4_-9bM4ccuBheeAmMNz9PVSAXsiP_P6hdwdHr39jCtR5NSLV9BuNbqdOc80qRajgXczxRBNCjh6QmbtsE_2q9TBsGZ-YdBfuGO3_L_ovgsEuqL5cMnTUHybxyvNj4bWBVMjYRWM=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmoIHFX2uHyYpAP0kuVWlsgPv9PLn0P-5SZA3dOS5O4TfefdTXiwrj_N-mKqoyfeUUsAwHNZv1qkYh_QaYI1eIHO9ng3rBjGSUEPygqzFL0etURmD5959AQeM62_HmqNBu66Oq_ZduKg2Oe=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn759LhoJKnIxAroFV5F5o1dEoQoSiSIEFkDe4DQeVEUu8LO8cExnO78NUvU8UIkcAhfiqhK1LlN_fRUsjRA-dAb0FzgpE7bkVAnFNb3B4oNRgPAnorwxtc5hWv5h_6QtP1pCNeA3aXpaHO=w1600-h1200-k-no"],
  ),
  dict(
    slug="yasir-garage-door", name="Yasir Garage Door Installation", name_url="Yasir%20Garage%20Door",
    city="Brampton", phone="416-268-0410", phone_tel="4162680410", wa_tel="14162680410",
    email="yasirgaragedoor143@gmail.com", rating="5.0", reviews="13", years="Local crew", years_label="Brampton-based",
    logo="YG", niche_label="Garage Door Company", schema_type="HomeAndConstructionBusiness",
    services_h2="Garage door work, done right the first time",
    hero_headline="Five 5-star reviews in one day. Still no reply.",
    tagline="Garage door installation, spring repair, and service across Brampton, run personally by Yasir — the same technician contractors themselves refer their own clients to.",
    about="Yasir Garage Door Installation is a hands-on, owner-operated crew serving Brampton. Contractors who work alongside Yasir on other jobs refer their own clients to him directly, and reviewers consistently call out his clean, careful installs.",
    services=[("Garage Door Installation","New garage door installation, guided from style to color to features."),
              ("Spring & Cable Repair","Fast, safe repair for broken springs and snapped cables."),
              ("Opener Installation","Installation of new openers and remotes."),
              ("Residential Service","General garage door repair and tune-ups for Brampton homes."),
              ("Emergency Call-Outs","Prompt response when a door stops working."),
              ("Free Estimates","A straight quote before any work starts.")],
    testimonials=[("As a contractor, I frequently receive inquiries about garage doors, and I always recommend Yasir. I had a great experience when I hired him for a previous job, and he even offered me the best price. Yasir and his team did an outstanding job installing a new garage door for me. I couldn't have asked for a better experience, and I highly recommend Yasir Garage Door Inc. to anyone.","Weziz Renovations","WR"),
                  ("It's great to find someone who is reliable, skilled, and takes pride in what he does. We would definitely recommend Yasir to anyone looking for garage door installation or service. 5 stars! Highly recommend.","Omer Azhar","OA"),
                  ("Wonderful experience, nice attitude toward work, excellent job done, will refer for sure.","Imran Salim","IS")],
    gallery_captions=["New door installation","Spring repair, Brampton","Opener setup","Residential service call"],
    primary="#2b2f36", primary_dark="#1c1f24", accent="#3f8fce",
    hook="Five different customers left 5-star reviews on the exact same day last week, one of them a contractor who refers his own clients to you. None of the five have a reply yet.",
    faqs=[("Do you install new garage doors?","Yes, we handle full installation and can guide you through style, color, and feature choices."),
          ("Can you repair a broken spring or cable?","Yes, spring and cable repair is one of our most common calls, handled safely and quickly."),
          ("Do you offer free estimates?","Yes, we give a straight quote before any work starts."),
          ("What areas do you serve?","We're based in Brampton and serve the surrounding area.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkQJSPwqF3n3qeXtC8R1w6gGoeecAkMS1fgA8xX66OIYXYnni6W_DWfRed5XPqd_zMqjKcLLM2eRAPmnUAzaEMA4ZA9cOFa-83VLKucMBCUJNiZY91dqbD9q5sdlT6tDOtErXfZrOdsBQs=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnRhty-9_BQeyJz5WxCrQKXMfmEc3MtPEWXxR6WtnQKBZ9a0JUP3yTY1Ydg2xQdJFjITyvl2g-tsugc-qFYkWDaLIlP7_w4TTE3S6hoOseFjG8kpX6RzIH1w03I17VemsmWWYWFSR8p0ao=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkBN6wQSr5W4EY-81FJBBzrEh8AR55moxKAahQeDthxWI0-7hg306CivZ2mr1loBhXDp_wNUTj-95HJeXtUXMfBy4TeNw6mBV6zl41kYBZEoNfJeKXkUdpzz60b8Mi8z4WJ2Nw_rEE8TJU=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn8ztnbHNgAqgZzjMdRJi4uorMJdFZxMsYaS6EWqJOweY18PB3mo_kIr_iLjmBc5Ren7l8fl3yig1gHAYKcEDX2I31wNAlqpCk20B0Jlyva-roqqsuuWQEdg6R6yPnRApHEgpBRQeFqduV3=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmo_qbwm-hrfL6nm_zNUJG_bi9O6BGU5acSbxyyq_d-TKCMqF3TzNdYujT2JfIzSIYvpHghYWlvEZEaXcGKhRLMkyPWS0yQk3XfRkg5hOqlTjzwA5DkvKhzj89a0Zi88i8e5vP78jwsrZ5-=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk4W42xAN9jVs7_NInZx7l2jniL6fnZCiK4RNG7S5Vu0g-13NjhewxCV_zojcH57ZQU81X8MEjdne2gdawpMmqMEDoC4aGCj-EySET-oGXY_vHRrZbtp-X4v6onp-bq8knmhdxe3ibE_Hk=w1600-h1200-k-no"],
  ),
  dict(
    slug="ace-garage-door", name="Ace Garage Door Services", name_url="Ace%20Garage%20Door",
    city="Mississauga", phone="289-937-1645", phone_tel="2899371645", wa_tel="12899371645",
    email="ameen@acegaragedoorservice.ca", rating="5.0", reviews="43", years="Trusted crew", years_label="GTA-based",
    logo="AG", niche_label="Garage Door Company", schema_type="HomeAndConstructionBusiness",
    services_h2="Garage door work, done right the first time",
    hero_headline="Ameen keeps getting named. The replies don't.",
    tagline="Affordable, professional garage door installation and repair across Mississauga and Toronto, with technician Ameen personally handling most jobs.",
    about="Ace Garage Door Services provides installation, repair, and maintenance across Mississauga and Toronto. Reviewers consistently name technician Ameen specifically for fair pricing and thorough, professional repairs.",
    services=[("Garage Door Installation","Professional installation for every door type and style."),
              ("Spring & Cable Repair","Safe, fast repair for broken springs and cables."),
              ("Roller & Track Repair","Fixing sticking, off-track, or noisy doors."),
              ("Opener Repair & Install","Keypad, remote, and opener installation and repair."),
              ("Emergency Repairs","Quick, reliable fixes when you need them most."),
              ("Free Estimates","A fair, upfront quote before any work begins.")],
    testimonials=[("My garage door needed a keypad and Ace was a professional and efficient technician. He came and installed the new equipment and had it working in no time. Highly recommend their services and trust their work. Cost was reasonable and fair as well. Great customer service!","Aisha Yasin","AY"),
                  ("Ameen is a very professional and knowledgeable technician. He adjusted the garage door springs, properly released the tension on the door, and replaced the rollers and cable ropes. I was very impressed with his workmanship, professionalism, and reasonable pricing.","William Rosario","WR"),
                  ("Fantastic service from start to finish. They replaced our broken spring and tuned up the whole system. Works like new!","Cris","C")],
    gallery_captions=["Keypad & opener install","Spring & tension repair","Roller replacement","Mississauga service call"],
    primary="#1f2937", primary_dark="#131a24", accent="#2f9e6e",
    hook="Four of your last five reviews — including two from this week — don't have a reply yet, and three of them name Ameen specifically for fair pricing and careful work.",
    faqs=[("Do you repair broken garage door springs?","Yes, spring and cable repair is one of our core services, handled safely and quickly."),
          ("Do you install keypads and openers?","Yes, we install and repair keypads, remotes, and opener systems."),
          ("Do you offer free estimates?","Yes, we give a fair, upfront quote before any work begins."),
          ("What areas do you serve?","We serve Mississauga and the greater Toronto area.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlUMGo8SBBcPQg1FuDgXVC7X7evALlPWDil6YodUZ8wDMHq3WVmmWRmlx5KiM7WBZJygz_W-ZkxoF26wNoXa0V_2nB3m1PN0wNLsQdfHH2KpDo77UcvCwBB6TyGPMkGzWc8S8qW0Wg1lAD-=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkaRvxEwE-ORR_CDGcNC0HdzPzDUhvNi4qM36rrLWo_mtH3-vLCZ3m8gfjIuA1AsgV7GkysB1SNzlnCcieQUUnN26Ldywss7Jmxj1c6Wz8aZZFxpUazGCzHWoK6Ybt3Jpxi0uUwSQL2MoL7=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlSBLtrNhNM2D-NOB5Byiabre2xb5MqzNgKJ1uzEYuXPAsbriGyeyTWxiUz5Y2R_JoETXhcgVOMUMYabllppPMvsgOcynJOJ50G8ufJlm29bUlHWDG4Nxz2kup3COkpt4rpjQ5RnJwJgvk=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnSpIE7SzB83AvZzx3zvEmXH6LBtGHNnWZ00Yv5TI3WqUNsuFaBoRdleXwCHMTR7gja5pSbzFq0Q9Nq3UxxBjKHZj9CS33NslNqz3EuPPfdCSJ-0uWWmZ1UgrzR6BLyvK-50zxTpgIApbI=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnr_xbAhKLyEYWTgpdLmEVUrKOL_b6ZX5W32J0IH7MRyIpiN_to7b8TWnyJ_5icgol8pZuo8yyx_ZhapqFUzbCPAFrrTWfMwbWHs8sLbOP_ECXPLt2EwvM7-jjqEL1CEcqqBlCxVgoVHMEt=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWklB8hYhLDtAveVEZyCxnSAc1TIBXmpsOVRkiiVIf6KGbuqatAT7r-CYns8lc5f2udQHJsyEdf07TwE8hAIT8enszWEDatdLu4EsYT-Mep2tXwhRERCQttcJYdyu0Fpa-rfcuTpITHVEV7p=w1600-h1200-k-no"],
  ),
  dict(
    slug="ysf-appliances-repair", name="YSF Appliances Repair Inc.", name_url="YSF%20Appliances%20Repair",
    city="Mississauga", phone="647-470-3410", phone_tel="6474703410", wa_tel="16474703410",
    email="service@ysfappliancesrepair.com", rating="4.9", reviews="14", years="Trusted locally", years_label="GTA-based",
    logo="YS", niche_label="Appliance Repair", schema_type="HomeAndConstructionBusiness",
    services_h2="Appliance repairs, done right the first time",
    hero_headline="“You now have a customer for life.” Still no reply.",
    tagline="Fridge, washer, dryer, and furnace repair across the GTA, run personally by Yusuf — the technician customers call back by name every time.",
    about="YSF Appliances Repair is Yusuf's own operation, serving Mississauga and the GTA. Customers consistently describe him as honest, thorough, and the first call after another repair company couldn't fix the problem.",
    services=[("Refrigerator Repair","Diagnosing and fixing fridges other repair visits couldn't solve."),
              ("Washer & Dryer Repair","Fast, honest repair for washers and dryers."),
              ("Furnace Repair","Furnace diagnostics and repair alongside appliance work."),
              ("Same-Day Service","Most calls get a same-day or next-day visit."),
              ("Honest Diagnostics","No unnecessary parts or repairs, ever."),
              ("Free Estimates","A clear price before any work begins.")],
    testimonials=[("We had Yusuf come to look at our fridge yesterday...after I had another appliance repair person come and they basically did nothing. Yusuf was on time, extremely knowledgeable and fixed the problem. Honesty and integrity mean a lot in this day and age and Yusuf is both of those things. You now have a customer for life.","Richard Hartlin","RH"),
                  ("We had an outstanding experience with Yosef from YSF Appliances Repair Inc.! He fixed our dryer quickly and professionally, and the whole process was seamless from start to finish. What truly stood out was his honesty and pricing—amazingly fair, especially given the high quality of work.","Adam B.","AB"),
                  ("Yusuf is excellent in diagnosing the problems. I had 2 guys try to fix my washing machine with no success until Yusuf came and fixed the problem. He is always thorough, honest and very professional. I strongly recommend his excellent service to everyone!!!","Iryna Vyslotska","IV")],
    gallery_captions=["Refrigerator diagnostics","Washer repair, Mississauga","Dryer service call","Furnace repair visit"],
    primary="#233a4d", primary_dark="#162431", accent="#d9a441",
    hook="One reviewer called Yusuf's work 'a customer for life' after another company gave up on the same fridge — and none of your last five reviews, going back almost a year, have a reply from the business.",
    faqs=[("Do you repair refrigerators?","Yes, refrigerator diagnostics and repair is one of our most common calls."),
          ("Can you fix washers and dryers other companies couldn't?","Yes — several customers came to us after another repair visit didn't solve the problem."),
          ("Do you offer same-day service?","Most calls get a same-day or next-day visit."),
          ("Do you offer free estimates?","Yes, we give a clear price before any work begins.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlR-QzZV0ix9ubxmU50kqbcOpWB8lyORCPBx3fHrVCy7qv-6ACWfJhsc-9obyZ19twUBF76lqyje9AKEwN3C_IPhvxBE2f_glYyUXxXOV0WwEu4pHradECvJgIGc4-sxOrldjY=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmyYYfOMloURvumzvVOdfVck-UMzK0P8SOFh7UnRN-8weF-Iulo0s-mEvDSESrn0942jd-wv4TZZ7yL7umaRoGpzODroVobx8sPZ81rd3svvJcyybw6GFMFBZrN-RWVRpF_UqZH=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkAoyYzmFbrwOwyc36viiHRD-D_b576effUHG363IZvNKPGfbtklyhoNwg6B3akgx6LpMwMFj0FNL_0SlAXF9__PyBkdxshC810ycinv_1s-LgwqFMI9TBsuVE-r2kFijMGLBBT7PF0uXw2=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkSVxyvv40Yabzg5RqKr4sR5cwZnSTTehGsxZDcBp57YNk_j0M7JtdrZwaholbOVoFp0tPq-TsS1JbdtG_xgh7imhEMWKDcHd0uOXcfoheFw-M3eLbzekL1ncDOnQV-4qphQisEDWSwEM1B=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmX2Wi7hvZGI_31Wa2n3nW2r_6TdZKnNfzkdN3tNvzGmA0LXaRTWRAhcg6y4QEeNvDztLEMfAz9XO1Fwk0Zdb5l9eXJ0Yz2uQy9hMRAVueNpjMG4jsaCit7APj7gZSmf_jD6LY-dwJLRxJS=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnfZXcGrWkzA8yZJitE2-JQOTjqqL6Jr1rtCUIxibv20bhw43G98HvWT4fKMcqgQbaqVgtwWSLbiVTw3kAB-6ADJVwAHl3bfqNiFvKGd8odI6lbrAFnPNhM6X7IZQ_io22QEp2IAQ=w1600-h1200-k-no"],
  ),
  dict(
    slug="furnace-ac-experts", name="Furnace & AC Experts", name_url="Furnace%20%26%20AC%20Experts",
    city="Mississauga", phone="905-595-0505", phone_tel="9055950505", wa_tel="19055950505",
    email="info@furnaceacexperts.ca", rating="4.8", reviews="413", years="413+ reviews", years_label="Google reviews",
    logo="FA", niche_label="HVAC Company", schema_type="HVACBusiness",
    services_h2="HVAC work, done right the first time",
    hero_headline="Three new 5-star reviews this week. No replies yet.",
    tagline="Furnace and air conditioning repair, installation, and maintenance across Mississauga, backed by 413 Google reviews at 4.8 stars.",
    about="Furnace & AC Experts handles furnace and AC repair, installation, and maintenance across Mississauga and the GTA, with technicians like Asif and Jayden regularly named directly by customers for knowledgeable, courteous service.",
    services=[("Furnace Repair","Fast, accurate furnace diagnostics and repair."),
              ("AC Repair & Installation","Air conditioning repair and full system installation."),
              ("Furnace Installation","New furnace installation for homes across the GTA."),
              ("Maintenance Plans","Seasonal tune-ups to keep your system running efficiently."),
              ("Emergency Service","Fast response when heating or cooling stops working."),
              ("Free Quotes","A clear price before any work begins.")],
    testimonials=[("Asif did an outstanding job. He was professional, friendly, and very knowledgeable about HVAC systems.","Susan Roach","SR"),
                  ("Great service from Furnace & AC Experts. They responded quickly and provided a quality repair at a fair price.","Connie Walker","CW"),
                  ("Jayden was courteous and efficient. He explained what needed to be done and completed the repair without any hassle.","Helen James","HJ")],
    gallery_captions=["Furnace repair, Mississauga","AC system service","Furnace installation","Maintenance visit"],
    primary="#1c2e3d", primary_dark="#11202b", accent="#e08a3c",
    hook="Three different customers left detailed 5-star reviews just this week — Susan, Connie, and Helen, each naming a technician by name — and none of them have a reply yet.",
    faqs=[("Do you repair furnaces?","Yes, furnace diagnostics and repair is one of our core services."),
          ("Do you install new AC systems?","Yes, we handle full air conditioning installation as well as repair."),
          ("Do you offer maintenance plans?","Yes, seasonal tune-ups help keep your system running efficiently."),
          ("Do you offer emergency service?","Yes, we respond quickly when heating or cooling stops working.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlkAeoSU-9NaqYYMipiagjvqeyFCU8GILT18lvIEnLTDSIEzUfz4Vk3wLLd7SREuDDgvmWLNrSIRCtiNRUt7WwtTDQpzEUl3AdFF7udemQVVMkzEIgOnseZpN8T7XCMYEYMc3WjUQ=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnpCU5C7Xsm-SNvWq-p-Rv2c6Y5QnoCI352Yr9BuRdwmKX5AGNHDBNKAbitksX4nekFmyc6x13vBXcU0ub1YWS-99rZX9Hkb1EKFPgQ3c76gDOZUCMPuL0fOMK9ooxxNwK6isqx-FZt_0kI=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk9jXfUDSMko26Pc2zk86rTkhcIb_vparODMTsW1TS1fInzjE4VcmERg2K0cREMN1SfCOFfXm3eXYth0xzfJhBdPz-sbFhtLxQgy31p_vqQ8Pp_Wfaipf85le0lya2Kfi8Xp4mF=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmj_NG45jbzeIumQzrzSkOM9qBJb_1KSVgOxCL59T-K6FBrumDu3_jhydwBidW_ZaiHbsgQLMF5eI_6-EcCKNFr7BJ4EGpDxib7bWn7f9nVNFtYi7HsnnV_w6OIVmtq7h_6GDSvIfvKfRmc=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkEFnMmGLXYJuysGai54FSNezWae5acvLfnE8sznCPVjGPCSwlXfLsIlOOVVdbn9c1Bc85q2d_koBV4pgTUJ9c9l4o-gWGEbUcZUdQy-fKJc3n9q9Sly-4AIpv1s-US7deU_LM8Qw=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk1Vh75PT5k4d1yXmxNY7BMBEQiwCxggZemonGp7cw9onA8Q4HBGjj21ykF_yMAX3e6iQDCiuRVEVZVID3Dg2JRxCm5nE6yhiOCF5GIYITvj2CUt2YyeWYwNgWA97K9aLNDgDWy=w1600-h1200-k-no"],
  ),
  dict(
    slug="green-heating-air", name="Green Heating and Air Inc.", name_url="Green%20Heating%20and%20Air",
    city="Mississauga", phone="416-627-7724", phone_tel="4166277724", wa_tel="14166277724",
    email="info@greenheatingandair.ca", rating="4.9", reviews="157", years="157+ reviews", years_label="Google reviews",
    logo="GH", niche_label="HVAC Company", schema_type="HVACBusiness",
    services_h2="HVAC work, done right the first time",
    hero_headline="Older reviews got a reply. This week's two didn't.",
    tagline="Heating and air conditioning repair, installation, and boiler service across Mississauga, with Hassan and the team handling everything from same-day AC fixes to full boiler replacements.",
    about="Green Heating and Air handles HVAC and boiler work across Mississauga, with Hassan personally following up on installs and repairs. Customers highlight same-day emergency response and thorough after-the-fact check-ins.",
    services=[("AC Repair","Same-day diagnostics and repair for air conditioning."),
              ("Boiler Installation","Full boiler and hot water tank sourcing and installation."),
              ("Furnace Service","Furnace repair and maintenance for GTA homes."),
              ("Thermostat Installation","Installation of modern, efficient thermostats."),
              ("Emergency Service","Fast response when heating or cooling fails."),
              ("Preventative Maintenance","Seasonal cleaning and tune-ups to avoid breakdowns.")],
    testimonials=[("Hassan from Green Heating & Air was an absolute lifesaver today! My AC stopped working over the weekend, and he responded quickly, diagnosed the issue right away, and had my unit up and running in no time. He even took the time to perform some preventative maintenance and clean the unit.","Stacey Salmon","SS"),
                  ("We were having issues with our residential boiler and hot water tank. We needed a new boiler system, and the company was able to source it and install it same day. The crew did excellent work and didn't leave until everything was working properly.","Crystal Smith","CS"),
                  ("Fantastic service and good advice. The technician was very knowledgeable and professional. The thermostats installed look great!","Jaco Becker","JB")],
    gallery_captions=["AC repair, Mississauga","Boiler installation","Thermostat upgrade","Furnace service call"],
    primary="#20362c", primary_dark="#14231c", accent="#5aa06a",
    hook="Jaco and Afework both left 5-star reviews this month and neither has a reply yet, even though a few older reviews eventually got a response from the business a few weeks later.",
    faqs=[("Do you install boilers?","Yes, we source and install full boiler and hot water tank systems, including same-day when needed."),
          ("Do you offer emergency AC repair?","Yes, we respond quickly when air conditioning fails, including weekends."),
          ("Do you install thermostats?","Yes, we install modern, efficient thermostats as part of our HVAC work."),
          ("Do you offer preventative maintenance?","Yes, seasonal cleaning and tune-ups help avoid breakdowns.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmOV31Jah8zjTrh99Cr15w2EIRMDX3IMo6Gq_F72XE8AhJ6lLC-KBvea9YzH-Yu8xhx6_naSRRaEy0X6AlVMkm3aZJ8PiU_gDcE0lo_virtieRrXWWh8YF9gvDIZ-M_mxBfF4fHAF4oL4-9=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnsta4yDZH7g2iSU3OY0QJjcvtygJqMMNAV3KfttYmLFtAc75pnWlIEAiIWrHtbYFnHHH_I3SnC77xOXdCh5t2a8fkgnBpdUPaebMhq33ReN1NYVupdZJGUVnXLygZDRlAquNM1=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkYjwGkp2RrE6SYCl8zCl19cjDHmPtyVyjK_oPdndf13BK-V7p2E5CH10w9TzHwyvOp4o5f6oR7_zkMeR0MxtigdxtKeVQ1puMHN5Bb2baN1w-aG73HF3Dt1NWNpZrxMJt1N8E=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlzjukjpHfx8pzYT8TCDy1xfzH2ARl_s3O-iowIkZPHk0j2U6oRG8bklco6CP3o-QKI3NMQYgf2MPCHWc57K3xTrtEMUQphr4_AM3AKBAQOHunrMEVu_fbPZEbAL8QYooDxbB28WWz_dZii=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmSaPHBaTuC3iP4Ck2Lz_OaBHh7cS7EV2JixtW1k-vAU2imbDV3VWOHFrcbQ1O3SO-NW4Cb_8Fb6dLKijbK0zE-QHXXDmcoc4EumXigB5Zoz6x7vmcVJrU_8XdHkwMaOkQjdeyl=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlG-2FbgOq53kgVPNenpsyTpiGZ-14y2OiutLwxX1yl_xjojmU2JjlZ-ddEOBihy2eo7IjrggutVlWZdG5PcyiK49wjEYSUSCbFZnGKiZqBKA5HItCOqruH4CqqUmWoavALLv0=w1600-h1200-k-no"],
  ),
  dict(
    slug="absolute-comfort-hvac", name="Absolute Comfort Heating & Air Conditioning", name_url="Absolute%20Comfort%20HVAC",
    city="Mississauga", phone="905-271-2911", phone_tel="9052712911", wa_tel="19052712911",
    email="info@absolutecomfort.ca", rating="4.9", reviews="227", years="227+ reviews", years_label="Google reviews",
    logo="AC", niche_label="HVAC Company", schema_type="HVACBusiness",
    services_h2="HVAC work, done right the first time",
    hero_headline="Five 5-star reviews this month. All unanswered.",
    tagline="Heating and air conditioning repair and maintenance across Mississauga, with Gary as the regular technician customers ask for by name.",
    about="Absolute Comfort Heating & Air Conditioning has served Mississauga homes for years, with Gary as the familiar face behind most repeat visits — customers regularly note he's 'our regular guy' who knows their system.",
    services=[("AC Repair","Diagnostics and repair for residential air conditioning."),
              ("Furnace Repair","Furnace troubleshooting and repair."),
              ("Seasonal Maintenance","Regular tune-ups to keep systems running efficiently."),
              ("System Installation","New furnace and AC system installation."),
              ("Emergency Service","Fast response for heating and cooling failures."),
              ("Free Estimates","A clear price before any work begins.")],
    testimonials=[("Great responsive service. Always a pleasure to deal with.","Stephen Rowe","SR"),
                  ("Helpful, knowledgeable, friendly and efficient, excellent work thanks.","John G. MacKay","JM"),
                  ("Great service, our regular guy — he seemed to know his stuff. Fortunately I was home when he was doing the service, my wife said he was very courteous and thorough. A good job as usual, it was an absolute pleasure to have you here again.","Lyall Johnston","LJ")],
    gallery_captions=["AC service, Mississauga","Furnace repair visit","Seasonal maintenance","System check"],
    primary="#1f3547", primary_dark="#13232f", accent="#4a9bd1",
    hook="Five different customers left 5-star reviews between August 4th and 20th — Stephen, John, Mona, Dan, and Maria — and none of them have a reply from the business yet.",
    faqs=[("Do you repair air conditioners?","Yes, AC diagnostics and repair is one of our core services."),
          ("Do you offer seasonal maintenance?","Yes, regular tune-ups help keep your system running efficiently year-round."),
          ("Do you install new systems?","Yes, we handle new furnace and AC installation."),
          ("Do you offer emergency service?","Yes, we respond quickly to heating and cooling failures.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk3NNN5taEjS4pNrDi4Byh1ABKEod_c9qaxNeYXMFeXLy_OSQVxDyLxjxN3F-jLpApajdwsUxAIvsEakNxuqQb9xH-B-u7iYTrqeb332hC9bJwG3jzY2NT4OUyc3HHBAfOj-c5DZw=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWktKtTm6iycccCHAAMuGpTNok17Dk6Dbt1V0pmWpxyHt7QPr8ffdeLsJ_YDuuQXxp8-pzrvcs1-fxdwS8bXNCDAmgMOoLbjhdMFsUkU2bqE_o51lQ4Z5TL7oXAgwGtC2N0we9rG=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmRI965zbDoStb-yPkIDTclL27Qf0Z5LMignwuUniOyzmtIlrXyMgPiTXnTu5aXZwJ3IA9GzgqQH1dhV9t7DI1a0eVgg9bI8oN7FjwihbcSWB5D0IHbixgQhsb3V_g1RuBRQt0bVw=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQKJ6yCI6FA6yZHQq8SEjKRQiyq03TMDnpaZd1SUSHZpRUjtLk05MycyFK-7MoyEikizDW2gkkhXV97pz9IeS_HAz_3PwE7HwvsjPWhiaUFCr3IO2Uu4pqj8Ps_3aiIwTlFUZfvQ=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnhirrAXO8nFvAWWwlUU5ldQBwMWpV0ehx-PDsJe8IjNSGXPTtRkbTU2Htv_mu49S4t5MEaISKqE4d0-JbcNh-PKfkHOnsTBjGQC89C1I-G4pfB2Ie4YKtHMgRS9ITJZLJE2pNJ=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkASXCv7SnkcGneDoATB4r9oN_mnJJmC3jOewxmD0GAwQVEfHZgrGqk6jbjloj0V8_uZjB9Q8FrKl6IwKM6hCL75GnOu9ctHsX8FjDnjFyuSwJPP50E-HV1jVjPLrynvoN_3fn_=w1600-h1200-k-no"],
  ),
  dict(
    slug="gm-heating-cooling", name="GM Heating & Cooling", name_url="GM%20Heating%20%26%20Cooling",
    city="Brampton", phone="647-749-8899", phone_tel="6477498899", wa_tel="16477498899",
    email="info@gmheating.ca", rating="5.0", reviews="79", years="79+ reviews", years_label="Google reviews",
    logo="GM", niche_label="HVAC Company", schema_type="HVACBusiness",
    services_h2="HVAC work, done right the first time",
    hero_headline="A full week of 5-star reviews. All unanswered.",
    tagline="Residential and commercial furnace and AC installation and repair across Brampton, with Gurpreet, Jatin, and Anmol regularly named directly by customers.",
    about="GM Heating & Cooling handles residential and commercial HVAC work across Brampton, from R22 AC replacements to commercial furnace repair. Customers consistently name Gurpreet, Jatin, and Anmol for going beyond the basic fix.",
    services=[("AC Installation & Repair","New AC installation and repair, including older R22 unit replacement."),
              ("Furnace Repair","Residential and commercial furnace diagnostics and repair."),
              ("Commercial HVAC","HVAC service and repair for commercial properties."),
              ("System Replacement","Full system replacement for aging heating and cooling units."),
              ("Emergency Service","Fast response when heating or cooling fails."),
              ("Free Quotes","A clear price before any work begins.")],
    testimonials=[("I connected with GM Heating and Cooling through Facebook Marketplace to replace my 30-year-old R22 AC unit. Jatin and Anmoal did a great job with the installation and were professional, friendly, and efficient. Very happy with the service and the new AC. Highly recommend!","Bharat Lakhanpal","BL"),
                  ("I cannot rave more about this company. They were extremely professional and went way beyond to fix our issue and give us the best options. They literally went beyond my expectations.","Aisha Chapal","AC"),
                  ("Excellent service from GM Heating & Cooling! They came out to fix our commercial AC unit and got everything back up and running quickly. Professional, knowledgeable, reliable, and easy to deal with. Highly recommend them for commercial HVAC work!","Doggpound Martial Arts","DM")],
    gallery_captions=["AC unit replacement","Furnace repair, Brampton","Commercial HVAC service","Installation day"],
    primary="#243342", primary_dark="#16202a", accent="#d97f3a",
    hook="Five different reviews landed in the last two weeks — residential and commercial — and every single one is still sitting there without a reply.",
    faqs=[("Do you replace old AC units?","Yes, including older R22 units that need a full replacement."),
          ("Do you service commercial HVAC systems?","Yes, we handle commercial AC and furnace repair alongside residential work."),
          ("Do you offer emergency service?","Yes, we respond quickly when heating or cooling fails."),
          ("Do you offer free quotes?","Yes, we give a clear price before any work begins.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl1r2cqn5-sEJZfaqiWJgukJIe5Ni1HC4CjYPusnznix_J6bSZhZSa8d0yt5rs55I3W357ZlxwaCZW5h1CyI4A_-uGJM2AbC7x5Ja4QSen_5fb_d98402oCB0xaqQFMC50pBdQnfOE3LNQr=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlNAmuBghx75heVmi4iI3e60c5hXaOLkzjuH6cFOJoUfp8yXo-BJkNU6VA5QsO8fplRKBexMx8JOOz5_h1gAz_1QLQYO0KiDwfkkVa_KFUepcQ9gkIjamUVjxs46I87oE0BedR5AVMl3cE=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7PZbtC1oSmDRFr-4hEGE7GjgAk7cab6gUDsAkozdqu_FkvSAnNYjGhhramvSRoxkMGmFkLIyvG3L46Otnt1iBux4Fw2Ss_eMNlUgyl11WP75Nz4kXM1XMu5jSLB-6tzftT2M=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnQbH2FgSXsE0SF0Dn3YWiBL_nB4dbh751ezyDpJhpt6GNcMWBQNxqaVMmCOm_3wRZEyJo_wxaLyb26AxHQJwNxe_GLHUE3Zte54zfGn66izrGy0pWyNa2qcbxediE-kApbU-is8Q=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnFNfAWizbwiZa3Klai-GRjFqbJjT1AP-VAPKRut9XHffKbS-ZhjFNoETH54jVTk0tLc_WFGEE18o4l1wRPQkkE3mxm17p5lwPnn1eEH3p5ouo9Inm5q6dy0vNZRfkkIQ8mSA9p=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWld2tcgDyfWAXtVYH-bx_g8UouISpEQbo94jQArqlEZia-fRU3AoZckWGWZuB2qmKAtkSDmXX5qJCUVK73Gni0gv02vnITRwzCcRmXd1do9X3EqHRHB4YjqyTcrFluEyARyTKt4i78FuWl0=w1600-h1200-k-no"],
  ),
  dict(
    slug="top247-plumbing", name="Top 24/7 Plumbing", name_url="Top%2024/7%20Plumbing",
    city="Mississauga", phone="647-697-0314", phone_tel="6476970314", wa_tel="16476970314",
    email="info@top247plumbing.ca", rating="5.0", reviews="118", years="118+ reviews", years_label="Google reviews",
    logo="TP", niche_label="Plumber", schema_type="Plumber",
    services_h2="Plumbing work, done right the first time",
    hero_headline="Jimmy keeps getting thanked. Nobody replies.",
    tagline="24/7 residential plumbing across Mississauga — drain clearing, leak repair, and water heater service, with Jimmy as the technician customers keep recommending by name.",
    about="Top 24/7 Plumbing handles emergency and routine plumbing across Mississauga, available around the clock. Technician Jimmy is named specifically in the majority of recent reviews for clear explanations and clean, thorough work.",
    services=[("Drain Clearing","Clearing stubborn clogs in sinks, tubs, and main lines."),
              ("Leak Repair","Fast repair for leaking pipes and fixtures."),
              ("Water Heater Service","Repair and troubleshooting for water heaters."),
              ("Toilet Repair","Fixing running toilets and worn internal components."),
              ("24/7 Emergency Service","Available around the clock for urgent plumbing issues."),
              ("Free Estimates","A clear price before any work begins.")],
    testimonials=[("I had a wonderful experience with Top 24/7 Plumbing Mississauga when a major clog in my main sewer line caused multiple drains in my home to back up. Technician Jimmy arrived promptly, performed a thorough inspection, and quickly identified the source of the problem. His professionalism and attention to detail gave me complete confidence in the repair.","Kkaur","K"),
                  ("I had a fantastic experience with Top 24/7 Plumbing Mississauga when a pipe under my bathroom sink started leaking. Jimmy arrived promptly, conducted a thorough inspection, and quickly identified the source of the leak. The work area was left spotless, and the repair has held up perfectly.","Zaynab Binte Asad","ZA"),
                  ("Mahmoud was fantastic — came out right away, diagnosed the issue quickly, and fixed our toilet in about 30 minutes. Another company was telling us we needed to replace the entire toilet, but Mahmoud was honest and solved the actual problem instead.","Amar Chaudhary","AC")],
    gallery_captions=["Drain clearing, Mississauga","Leak repair","Water heater service","Toilet repair visit"],
    primary="#1c3548", primary_dark="#11222f", accent="#3fa8c9",
    hook="Five of your last six reviews name Jimmy specifically, in detail, and every single one is sitting there with zero reply from the business.",
    faqs=[("Do you offer 24/7 emergency plumbing?","Yes, we're available around the clock for urgent plumbing issues."),
          ("Can you clear a clogged main line?","Yes, drain clearing for sinks, tubs, and main lines is one of our most common calls."),
          ("Do you repair water heaters?","Yes, we diagnose and repair water heater issues."),
          ("Do you offer free estimates?","Yes, we give a clear price before any work begins.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnFANt1quYrD0ZZwu-ZOElDpYAQG1-HAercKJnOrFfn7dyyizA0PMGKAsVk0kyJy-4VEcXRdcjacH7cNZ7HjM95508_HktHwSAQTFNllg-ijzasZl_OMzhbrWjUGG4tUyo2KMrVGSiuK9w=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkNrnuhA95XWFCfSZBLv4P_a25ixBk_Lh6VYL9Jrjq80MLhAtEekQb6I9xU6fxT5K1po6GAiND7WxQ3k3NcKG7nXSq09cNw6xCBlgr4mi6NC-PaDXi5kcRlMs5EpsP6IE0dBUwENVI0k_11=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnnPW_NBbmzAM3NqX8ZoOTSILrBDVzKkXnvVMmzttzZV-mtLpQRw9HyoJ6b2n73Ffkhm9V5AkRspQfp1cmZDDVG_Hi8qil-ln6tISlgDU9knCMz25ToGW9OfFLEmhrRBC4rIjsETWYcXFqo=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmZXIyP38oqh55N16tnASAmBm6CSP53s1QQPlvERtI9PNJb9AjrwrfwCARC74FJjvSqbEoTvkHDMHFABAudRuz39jLlhnYO3nPdwijEcSZxfs360FeRCV5z_2yqlyFnUsmTljGujLUOeKY=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnLd-ua19CATUAKJJ1Wsy5PQktMZ3ZUqCLY8Qa5PEipWmVv_VsouTnY-Q_3SP32KbUB5FJ881xlntwYZ-X4ijfKuJpLQe2Z5z-FS2TIIgapoUt8WJRqYitlEYePqfcD4ETWqqFsk5UZ0Ts9=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlYuEgCqCQlmkR2YfcnyAOgVFxW7BxIokrPH8WG7VuYfHy2VfgJQSGuRZ5ITL7k2tLwsXEGc4rdQvFT9UN1NgMclvVJiDeTyFIKHJDSHx-nrpWIx3fM8ihSskCYQIQU1F-qa0vk9G9Rwoik=w1600-h1200-k-no"],
  ),
  dict(
    slug="lorne-park-plumbing", name="Lorne Park Plumbing", name_url="Lorne%20Park%20Plumbing",
    city="Mississauga", phone="647-360-8965", phone_tel="6473608965", wa_tel="16473608965",
    email="info@lorneparkplumbing.com", rating="5.0", reviews="62", years="62+ reviews", years_label="Google reviews",
    logo="LP", niche_label="Plumber", schema_type="Plumber",
    services_h2="Plumbing work, done right the first time",
    hero_headline="Six 5-star reviews in one week. Zero replies.",
    tagline="Residential plumbing across Mississauga's Lorne Park and surrounding neighborhoods, known for fast response and clear communication on every job.",
    about="Lorne Park Plumbing serves Mississauga homes with fast, well-communicated plumbing work, from clogged drains to full repairs. Reviewers consistently highlight response time and being kept informed throughout the job.",
    services=[("Drain Clearing","Fast clearing for clogged drains and slow-moving pipes."),
              ("Leak Repair","Locating and repairing leaks before they cause damage."),
              ("Fixture Repair & Install","Repair and installation for sinks, faucets, and fixtures."),
              ("Water Line Service","Repair and maintenance for residential water lines."),
              ("Emergency Response","Fast, same-day response for urgent plumbing issues."),
              ("Free Estimates","A clear price before any work begins.")],
    testimonials=[("The job was done exactly as promised, in a quick manner. The company was very easy to work with and communicated clearly throughout the process. Will be calling them again for future work, absolutely would recommend.","Lakshaan S.","LS"),
                  ("Great service! On time, well done and very well priced. Would recommend to anyone and everyone!","Francis James","FJ"),
                  ("Couldn't have asked for a better team. Amazing and would recommend to anyone.","Ajitabh Sodhi","AS")],
    gallery_captions=["Drain service, Lorne Park","Fixture repair","Leak repair visit","Residential plumbing call"],
    primary="#1e3a4a", primary_dark="#132530", accent="#3fa8c9",
    hook="Six different customers — Lakshaan, Francis, Zac, Michael, Ajitabh, and Yin — all left 5-star reviews the same week, and not one of them got a reply from the business.",
    faqs=[("How fast can you respond to a plumbing issue?","We're known for fast, same-day response on most residential calls."),
          ("Do you repair leaks?","Yes, locating and repairing leaks before they cause damage is a core part of what we do."),
          ("Do you install fixtures?","Yes, we repair and install sinks, faucets, and other fixtures."),
          ("Do you offer free estimates?","Yes, we give a clear price before any work begins.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkrmCgItRGUJeR7oT5O4jeIwf9AIWRbjc5k84GIYB_Fbik3BNodE-JkTOL2RZV70l83tyqjCNhoYltI2ycbQZgUyXBTV83fYVfLAUPnk6M2v1CeGlNyqMqeiXOZflb0teUxEaSJHkojNPOi=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlmU5CMTEpTXghIKC-CgB0QzSVcwxDj9wb6wal551LYYvfo4K3F7F8TEQpQ837AxLRkyYtFvyJtT51Cmm5f8FCUE8GY5t7B213HpiEtcD3BVCPgnU6LQUWyLg8rHJlJex2x5sUtEIpy1ZvW=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk7x1yVIhCPhwYFIuC6Uu0iHkXdbPkL52knFJaAT6bMyOWMN9NDeVNH-MJGOPnMMmn1rWQU7fpOMFXmcpLZenAjUApw7y3O6gIP-NjiqYsvrN877Pfpogqyh2SM4hOO_9f1RsehWAH2k_tn=w1600-h1200-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkW1aF4Mf9OIVcDlz9BKGqncDc3zxWVAyCLzrm6Bdl8wXDebIFm2_xSRG4XBWW8TyQNukM_So6Gd1CZnU6LCuU1QLJnt7LpRZLe2nZkt_mDsnPxIGE_JaAcDv8h5EtIqSMgnWVaGsv0Zhwo=w1600-h1200-k-no"],
    before_after=["https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnRnyqG84M9wICL2QJC5nPcM9OgHvh9peU4D1ZTBsPVV_o7937o1blshT81aGZl5SrsWvcEulvp_WSo_Q8RT72ud5_ZDMfnkKVxRmKj93C63feeQjv-RWIXs0cbECy7jXaFnuVcseL_SJ_r=w1600-h1200-k-no",
                  "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlkDgI-6NWlRq-fVvMs0Mpnv9PLgAwDSapZBeb-0yQW0BDRg4HHQoXidfuCDRX5kjcuNBHstrynca-DYZb87aXK_qSq8FZHiIe3_FSGObPVRY9_tMqOgCN4pCjLLDcBq8S34AQ-gNXoeRSk=w1600-h1200-k-no"],
  ),
]
