LEADS = [
  dict(
    slug="bigguy-electric", name="BigGuy Electric Inc.", name_url="BigGuy%20Electric",
    city="Brampton", phone="905-867-8017", phone_tel="9058678017", wa_tel="19058678017",
    email="info@bigguyelectricinc.com", rating="4.9", reviews="134", years="8+", years_label="Years serving {{CITY}}",
    logo="BG",
    hero_headline="134 five-star reviews. One name Brampton trusts.",
    tagline="Licensed commercial, industrial, and residential electricians in Brampton, the crew customers call by name for the jobs other companies won't take on short notice.",
    about="BigGuy Electric has served commercial, industrial, and residential clients across Brampton and the GTA since 2018, with Tico and Steve as the two names customers ask for by name. One customer's favorite story: Tico once showed up with coffee in hand during a snowstorm, knowing their kitchen was out of commission.",
    services=[("Commercial Electrical","Code-compliant electrical work for commercial properties across the GTA."),
              ("Industrial Electrical","Experienced with industrial power systems and equipment connections."),
              ("Residential Electrical","Everyday repairs, upgrades, and installations for Brampton homes."),
              ("24-Hour Emergency Service","Available around the clock, including holidays and weekends."),
              ("Outlet & Switch Repair","Fast, clean fixes for dead outlets and faulty switches."),
              ("Free Estimates","A straight quote before any work begins, no pressure.")],
    testimonials=[("Big Guy Electric: these guys are in a class of their own. Tico arrived on our doorstep the next morning with a coffee in hand, knowing we had no access to our kitchen. What kind of service is that?","David Perkins","DP"),
                  ("Steve from Big Guy helped us on a Sunday, after Christmas of all times. He took time away from his own life to help us when he was on his own time. People like Steve take customer service to another level.","LeVar Lashington-Francis","LL"),
                  ("Excellent service! Very professional, on time, and knowledgeable. The work was done neatly and everything was explained clearly.","Pallav Maggu","PM")],
    gallery_captions=["Outlet & switch repair, Brampton","Emergency call, Boxing Day","Residential electrical, GTA","On-site diagnostics"],
    primary="#26313d", primary_dark="#18212b", accent="#c9762f",
    hook="Your own site hasn't been touched since 2018, and it doesn't mention Tico, Steve, or a single one of your 134 five-star reviews. This version does.",
    faqs=[("Do you offer 24-hour emergency service?","Yes — BigGuy Electric provides 24-hour emergency electrical service, including holidays and weekends."),
          ("What areas do you serve?","We serve Brampton and the surrounding GTA for commercial, industrial, and residential electrical work."),
          ("Do you provide free estimates?","Yes, we provide a straight quote before any work begins, no pressure."),
          ("How long has BigGuy Electric been in business?","BigGuy Electric has served commercial, industrial, and residential clients across Brampton and the GTA since 2018.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWldl_HFGYWmLiTvM-JI5AVjtRGA_8rzJ2g-_WWjCSLqu1zr767D1SW2aO0FAWgkcMxOYLDNwA0XmG4He30UxVMzD_uTYFGz7UUcURdfWQOFlQyNyar9NOlfWKNlIl82FqFotfU=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWngqLB9fkF2Bik8xuJMPtc2BZcsO7FG5MCNjRXihvYUhhD6TcctWpRfz2k5tzCbLj7iMyoeevgEJ7wFsrQRhfp4VUxkZ5B6WJuj8z0FOuRzdBokBcAsoEUssG0SLaofD4YgHqx6=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlVDu07joRwRsCYT8Ns6De2U-_wxtlgEi4P5MewswXlUmrNiZGOB_11_dVz0_ZOjOlETvE6Yr3Er-0cgcxWw2Epu3i3kDmIwAkHht_oqpqjboHgp0-iaK9sarEYCPSdBeyZNBIs=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmwLGPO2YozTNQr255GDsU1T9FTd-YfaB8YefAkpTSYTClsh8mYBfJf3TxI20z15C1uQHmCAc7iyipk6MmcJcLG_kY5VTSlmGeMircpFr_KyJbLBuc_pLPeRZ9flpunC3EGyeVz=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlzfAbsZgqYOh4MophqlU0DX22jiQlv01kYgUKuvt-jmJKLyxa0Z5Sp1NjXgeu2zywdNs1RCOJwQN1neXF5PW23MHZLWVMhROHLH-L2acomxrny01IfjYbWD8xExnEkvr0hDGJz0A=w1920-h1080-k-no",
  ),
  dict(
    slug="jmc-electric", name="JMC Electric Ltd.", name_url="JMC%20Electric",
    city="Brampton", phone="905-451-1830", phone_tel="9054511830", wa_tel="19054511830",
    email="info@jmcelectric.ca", rating="4.9", reviews="174", years="25+", years_label="Years serving {{CITY}}",
    logo="JMC",
    hero_headline="Brampton's electrician since 1999. Still Joe's crew.",
    tagline="Award-winning electrical contractor operating in Brampton since 1999, handling residential, commercial, and new-build electrical work across the GTA.",
    about="JMC Electric has handled residential and commercial electrical work in Brampton since 1999, earning Top Choice and Best of Brampton recognition along the way. One customer, AOne Samosa, has been calling Joe for about 15 years and still says the workmanship is superb every time.",
    services=[("Residential Services","Installations, repairs, and upgrades for homes across Brampton."),
              ("Commercial Services","Electrical contracting for offices, retail, and commercial builds."),
              ("EV Charging","Certified installation for home and commercial EV chargers."),
              ("Fuse-to-Breaker Upgrades","Replacing outdated fuse panels with modern breaker panels."),
              ("New Construction Wiring","Code-compliant wiring for new residential and commercial builds."),
              ("Financing Available","Flexible payment plans for larger electrical projects.")],
    testimonials=[("We contacted JMC to replace our existing twist-in fuse panel with a breaker panel. From start to finish we couldn't be happier. We received a free quote beforehand and the panel was replaced at the price stated. A++!","C Cc","CC"),
                  ("Great work always JMC! Been dealing with Joe for about 15 years, always there when I need them. Workmanship is superb! Keep it up guys.","AOne Samosa","AS"),
                  ("I needed the wiring to our dishwasher moved to allow it to sit flush under the countertop. I could not be more pleased with the results. Instantaneous reply, quick visit, and the two electricians were pleasant and efficient.","John Morgan","JM")],
    gallery_captions=["Fuse box to breaker upgrade","Kitchen appliance wiring","Panel replacement, Brampton","Residential service call"],
    primary="#1e3a3a", primary_dark="#122424", accent="#c9a227",
    hook="You've been operating since 1999, but your site's homepage doesn't say so anywhere, and none of your 174 reviews are shown either. Twenty-five years of trust deserves more than a contact form.",
    faqs=[("How long has JMC Electric been in business?","JMC Electric has served Brampton since 1999 — over 25 years of residential and commercial electrical work."),
          ("Do you install EV chargers?","Yes, we're certified to install EV chargers for both home and commercial properties."),
          ("Do you offer financing?","Yes, we offer flexible payment plans for larger electrical projects."),
          ("What areas do you serve?","We serve Brampton and the greater Toronto area.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnCkKs-IXyFv7KMmPWrWfum8CuAHotckZofbgo9iDJw5-YC2QpZquDNeCsJRQiBkW8n8_f7_GLpRjWsM7dyKfstAag56RICu6kK2ptrttkhiE8jcFoLY4FYaLp9qc0f51L-_a7KtA=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlO7hunMhkAs-67bwD-jllZYjjmcFnu64zw_FjYMVUB7XTRnK8TQsJL5MwuCPetqk7nTZT5W4rze7hPBMNeE12MSyzZIknOnMHft2PvH3wqN_OnAxO5vKGYYVHAPqL5u-jgt8_oGg=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn1EAyK8j76nVWMrbspW86htH6kk0B4L_yGw5Mcmq6TyafOKVI-6lAHy3Cxp2zVILst_MF2QHAnIRJojafcjPfPi96FMFjEZ7cSCQcpRn0TIEMFga97fyAW8x0jEF9hEhIowAak-g=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmtWRsJLe1DxIvq_Yg3CKtuko2VpGS425ywD2UURw7AQCxjrhGUChj8-xHQTJxx0iuE8vtlrFi_8faaMLXPuuCqEaH4zCAaNCXpxtslR7372jaW0U094HR7wfgJJamzQ0SF2rBTVQ=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnr4luyp3Z_1r5aju3YD_42vyEbegoiLuO0GH2PfpzMWlXgrduX_c1mWd1N92ZXCS4F_4H2LZ-Sbg-pfWNGkWywjfrDtMbLcFw4sYnvisCg4oPQLbYNr2yDKicg16QY-rEECUsi=w1920-h1080-k-no",
  ),
  dict(
    slug="modern-electrical-contractors", name="Modern Electrical Contractors INC", name_url="Modern%20Electrical%20Contractors",
    city="Toronto", phone="647-983-5343", phone_tel="6479835343", wa_tel="16479835343",
    email="modernelectricalcontractorsinc@gmail.com", rating="5.0", reviews="71", years="GTA-Wide", years_label="Service coverage",
    logo="MEC",
    hero_headline="5.0 stars across every job in Toronto.",
    tagline="Toronto electricians handling everything from panel upgrades and solar tie-ins to same-day fixture repairs, with a perfect 5.0 rating across every job on record.",
    about="Modern Electrical Contractors handles residential and commercial electrical work across Toronto, from panel upgrades and solar tie-ins to same-day fixture repairs.",
    services=[("Panel Upgrades","200-amp panel upgrades for homes with growing power needs."),
              ("Solar Panel Tie-Ins","Electrical integration for residential solar panel systems."),
              ("Lighting & Fixture Repair","Fast, clean fixes and installs for kitchen and home lighting."),
              ("Residential Electrical","General electrical repairs and upgrades for Toronto homes."),
              ("Commercial Electrical","Electrical work for Toronto commercial properties."),
              ("Troubleshooting","Quick, accurate diagnosis for electrical issues of any kind.")],
    testimonials=[("Excellent experience with Modern Electrical Contractors! They did an outstanding job upgrading my parents' home to a 200-amp electrical panel and installing their solar panel system. The team was knowledgeable, reliable, and made sure everything was completed properly.","Abdul-Haqq Amin","AA"),
                  ("Excellent service from Modern Electrical Contractors Inc.! Andrew and Jaz were both incredibly friendly, professional, and efficient. They quickly fixed my kitchen light fixture and made the entire process smooth and stress-free.","Kelly Machado Alexander","KM"),
                  ("Simply the best experience. Especially the work and the cost. If you want your electrical work done right, these are the guys. Andrew is quite knowledgeable.","Ramesh P","RP")],
    gallery_captions=["200-amp panel upgrade","Solar panel electrical tie-in","Kitchen lighting repair","Residential service, Toronto"],
    primary="#1b3a5c", primary_dark="#11253c", accent="#3f8fce",
    hook="Your Google profile shows real, detailed 5.0-star reviews about panel upgrades and solar tie-ins, but the About page on your own site currently returns a 404. This version actually has one.",
    faqs=[("Do you work on solar panel installations?","Yes, we handle electrical integration for residential solar panel systems, including tie-ins."),
          ("What's your service area?","We serve Toronto and the surrounding GTA for residential and commercial electrical work."),
          ("Do you offer panel upgrades?","Yes, including 200-amp panel upgrades for homes with growing power needs."),
          ("Do you handle commercial electrical work?","Yes, we handle code-compliant commercial electrical work across Toronto.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm8zBXBlOgEu7aCLJhtyrqWw-MmYrD3APF1lEbGyzKGn8J2PJbyfj5PAOR8OVgzF5Z2UKzLHAObOOFqMqYxDu1yQawX8W7-MctygfICMYNQhZEimz_lzltIxlsGl55-4U1guiAQLMy2CItO=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWld0OgQuP68kVaXWACL24d4kTFMZ7fWNxdRKrlPTEtNjk5GAwzOTeA_MdokceE_eWMURD38GNXXprXP4BBlZUnccJ57jfVi1oMSEtpzbvdf14C-MGJIlo4zbqx1Y4G6FnpgDjQt2pkNDUiM=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWll9aI8-I5Km_vVgDBwz70Lgvyo4KxKAak4S_r6Vq1SsPKl-vpfkhmSWV7ovtnhMxkixVlRAy09AFmeJkQhqtOjByc5_N_i2yQznUluNje39xDYXwcyPGKsmC6ffUKkk7mZrsNuHnOieVgZ=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmAMvJ3sKsXaHdKcDVbk1Pz6-7r4-1RNOqq87yAat8P-mWiY_zniq577B8prEzlOoU6JI_2cry3qJ5TfrlOICOUGNfPLnppfdNhB7FM9ffn1a7tshK9a8umRWvUX0OEiwrvSqVGOIYeNRRC=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm8EGkCPAxZQtZCk2thRRqmKMjXZkwyT8nG9t_HIlAyynSczJ06Aqc7ZJ4zo988mLsYVF6qFINGn1DIWQVdT-mTpPQ9X8Nyi0oIcaHGckUkka4gIzFzfeOpGwFP3d2GMrmsUADKBmLaApc-=w1920-h1080-k-no",
  ),
  dict(
    slug="ontime-electrician", name="Ontime Electrician", name_url="Ontime%20Electrician",
    city="Toronto", phone="416-882-6000", phone_tel="4168826000", wa_tel="14168826000",
    email="info@ontime-electric.ca", rating="4.9", reviews="280", years="20+", years_label="Years serving {{CITY}}",
    logo="OE",
    hero_headline="20+ years, 280 reviews, licensed Master Electrician.",
    tagline="Licensed 24/7 electrical contractor serving Toronto and the GTA for over 20 years, led by a Master Electrician and backed by 280 Google reviews.",
    about="Ontime Electric is a licensed and insured electrical contractor led by a Master Electrician, serving Toronto and the GTA for over 20 years with 24/7 emergency coverage.",
    services=[("24/7 Emergency Service","Round-the-clock response for urgent electrical problems."),
              ("Panel Upgrades","100, 200, and 400-amp panel upgrades for growing power needs."),
              ("EV Charger Installation","Level 2 EV charger installs for all major vehicle brands."),
              ("Electrical Rewiring","Knob-and-tube and aluminum wiring replacement done to code."),
              ("Lighting & Potlights","Interior and exterior lighting, including full potlight installs."),
              ("Electrical Safety Inspections","Full inspections with ESA documentation provided.")],
    testimonials=[("Contacted Ontime Electric through a friend's referral. Sean and his crew installed 8 outdoor potlights plus a timer. They are an astounding team, very clean and organized. I'm simply thrilled with the results!","Behrooz","B"),
                  ("We needed an electrician in North York for a panel upgrade before adding an EV charger. The whole process was smoother than expected and the communication was great from the beginning. Everything was tested properly before they left.","Noah Shin","NS"),
                  ("We recently bought an older home in Toronto and wanted a licensed electrician to inspect some questionable wiring before renovations. Sean was very thorough and explained everything in simple terms, focused on safety instead of unnecessary upsells.","Arshan","AR")],
    gallery_captions=["60-potlight installation","EV charger install","Panel upgrade before EV charging","24/7 emergency call"],
    primary="#1f2937", primary_dark="#141b24", accent="#d94f3d",
    hook="Your site already does a lot right, real pricing ranges, real FAQs, a real Master Electrician credential. What it doesn't have is a single photo of the actual work. This version leads with that.",
    faqs=[("Are you available for emergencies?","Yes, Ontime Electrician provides 24/7 emergency response across Toronto and the GTA."),
          ("Is your team licensed?","Yes, we're a licensed and insured contractor led by a Master Electrician."),
          ("Do you provide ESA documentation?","Yes, our electrical safety inspections come with full ESA documentation."),
          ("How long have you been in business?","Ontime Electrician has served Toronto and the GTA for over 20 years.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWldz_cbB4Tf8A7rVPEKMjSOQKy1m5ZpKoTQRcAPRitovxG7zwwqWpH0nGLJZQ6fiAXyogfEz0RYIRnHXWhaMJj6eYytGFQtS_UYT1tMKJuylu8CeA7NQeK9yRUWOtZZRuw_3JHn=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlZFHT0elrFNLnFXQ8DEwGRLeOmsl_WKQgUYOA67Viu0I7QxoY5c8PXx5lTBrvnlO9jEEYWlL3vWvvIHh0AFvdcgaOKlOu5zZsEW4BnX7j1hlu6S3KfXREOLfRxGqpIsZsHhkNNnw=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmWo7abfbiLpk_thX8DDOODiy7MaGDagNiUfkyffb9U0zlDS4aipbtHMjFC-S4Zx3Zblt9GZcrb19EM8YBVSFtlmJ56KmCBFo1MWlrNadApY-XnOgH7X9mveHgc9VaLPnzaZUkGxw=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmI_4jq0_vawahPTmxsZDSl58UJjUj6f2sEbKuQsRJza7akrCEbQu8wtleNc_tUwDyNBARKuwQ9I-UYK1N04a71ZdbeJ8aCT0ZMvgllbtIG19cbu4KaPfEo19Rm3e6rXWJfYi7TPA=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmnqjn_ryGpm-DJ6Rtr7otMvn8Ib-Zk_NUEjloDbWSbQQWdkfL4LRDxZczcn2cVMC0wml9RyvAsxabY2t_v-6Uq5wdYoRh36y9pGFmanN9ApCQVTJYtPNVr1T9JvmjPgAiB4IWI=w1920-h1080-k-no",
  ),
  dict(
    slug="kronos-electrical", name="Kronos Electrical Contractors Ltd.", name_url="Kronos%20Electrical",
    city="Toronto", phone="416-579-1707", phone_tel="4165791707", wa_tel="14165791707",
    email="ourhomeelectrician@gmail.com", rating="4.7", reviews="86", years="20+", years_label="Years serving {{CITY}}",
    logo="KR",
    hero_headline="Toronto electricians since 2004. Twenty years trusted.",
    tagline="Toronto electrical contractor operating since 2004, built around one philosophy: inspect, respect, and correct, backed by a 10-year service warranty.",
    about="Kronos Electrical Contractors has served the GTA since 2004, built around the founder Stan's philosophy of Inspect, Respect, and Correct. Ask James Wanstall about the time Stan dropped by to fix a light switch, and didn't even charge him because it was an easy fix.",
    services=[("24/7 Emergency Service","Rapid response for urgent electrical failures across the GTA."),
              ("Panel Upgrades","Reliable panel upgrades backed by a 10-year warranty."),
              ("Aluminum Wiring Remediation","Safe remediation for older homes with aluminum wiring."),
              ("EV Charger Installation","Level 2 and Tesla charging station setup."),
              ("Commercial Contractor Solutions","Code-compliant electrical work for commercial spaces."),
              ("Service Mast Relocation","Utility service mast relocation and upgrades.")],
    testimonials=[("If you are looking for a competent electrician that operates with integrity, Kronos Electrical Contractors is the business to reach out to. Stan's patience, expertise, and professionalism resolving our whole-house power outage was absolutely exceptional.","Stephanie Asare","SA"),
                  ("My experience with Stan, owner and operator at Kronos Electric, was fabulous. After my initial call Stan was working on our electrical emergency within 30 minutes. We are very appreciative and would highly recommend him.","Paul Herd","PH"),
                  ("Could not recommend highly enough. Alex was polite, efficient and very fair on pricing. Stan dropped by to fix a light switch and as it was an easy fix he didn't even charge us. You can't beat that.","James Wanstall","JW")],
    gallery_captions=["Whole-house breaker troubleshooting","Restaurant renovation wiring","Service mast relocation","Commercial upgrade, old building"],
    primary="#2e2a24", primary_dark="#1c1a16", accent="#b8863b",
    hook="Your homepage still shows placeholder stats reading \"0%\" and \"0+\", two decades after you started the company. This version replaces the placeholders with what's actually true: 86 five-star reviews and real client stories.",
    faqs=[("Do you offer a warranty on your work?","Yes, our panel upgrades and electrical work are backed by a 10-year service warranty."),
          ("Do you handle aluminum wiring?","Yes, we provide safe remediation for older homes with aluminum wiring."),
          ("Are you available for emergencies?","Yes, we offer 24/7 emergency response for urgent electrical failures across the GTA."),
          ("How long has Kronos been in business?","Kronos Electrical Contractors has served the GTA since 2004.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnrqXj0A3RIr-Gb6H45XPST1RcJH6UCN9sLeHVvBh7il3HO-AapUIYJ7-9JxP0zMrJU-AFpqAoMbC6BgJKBGp6W4VIoPPHR_i9_BelfsIS5ZtzBX9RytchE0wLCWvnm_AM9Piqsn3Yq4joD=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnFwUHQhSikqP7VHXbskxY2Ewb8fGtoGFt0jZqvYes5t9adXVAXx3XHjgeUFxxoARJqsje8uCYKpEL8MQBjR5qIsMzJFMxvCqsYRIqzZUDIKfUy1Zznz5uXkoXlJ_WoffQZswVkQ_TWr4WR=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmIvKy1T8mz6trwyf5wH4Drr6IwnQsXSbFTwJcR0Ia6tJh2CkYsdpz6VBh1l1vDJBD6yVjxNL1ee6Z8zKRxCEEqBq3ijn5HfPlHOc2qW9M2oSDAAv-EGu1puuGZq7KAAGv2XA8sjjlJsnK7=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmfcW364FS73y85GTi4abexPhcYUddaDbYDlP9kl4PTsSwI5Z3DW0IclnAvQxkj-BdmVR5xOw19uhD0EsHZm7-xdX7mxQHmU71lfd1geERwoQ_ytJYwlQ0dB28qS2Qg1z4weHux=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmI7b3MHzwJSZi6LRyW6LZ0dhUgZnpOdbtXWkLlYXJVwzHtcG2yGnLcRSCgqMsfxVAXg7iOE3LIj4WY-XIuQ7KTmx3ld7xsKBlhxwcRxZul31qqW-SGhBNcajnp_tBNUJox4Qv0cAR4eI8x=w1920-h1080-k-no",
  ),
  dict(
    slug="trust-electric-works", name="Trust Electric Works", name_url="Trust%20Electric%20Works",
    city="Mississauga", phone="647-785-5208", phone_tel="6477855208", wa_tel="16477855208",
    email="info@trustelectricworks.com", rating="4.7", reviews="155", years="24/7", years_label="Emergency service",
    logo="TE",
    hero_headline="155 five-star reviews. A name taken literally.",
    tagline="Family-owned electrical contractor serving Mississauga, Oakville, Milton, and Brampton with 24/7 emergency service and same-day ESA inspections.",
    about="Trust Electric Works is a family-owned electrical contractor serving Mississauga, Oakville, Milton, and Brampton, with 24/7 emergency availability.",
    services=[("EV Charger Installation","Reliable EV charging installs for homes across the GTA."),
              ("Panel Upgrades","Fuse, 100, and 200-amp panel upgrades, done right the first time."),
              ("House Rewiring","Full rewiring for renovations and older homes."),
              ("Troubleshooting","Fast diagnosis for electrical faults of any kind."),
              ("Renovations Electrical","Electrical work for kitchen, basement, and full-home renovations."),
              ("Emergency Service","24/7 availability for urgent electrical problems.")],
    testimonials=[("I hired Trust Electric Works to install an EV charger at my home. The pricing was no-frills, they took great care of the property, gave a professional warranty and certificate, and were very responsive. I would recommend them with no reservations.","Fadi Atassi","FA"),
                  ("I had an electrical emergency and contacted Khaled from Trust Electric Works. His company is appropriately named, he is trustworthy, honest, and compassionate. His price was unbelievable and he fixed all my electrical problems the same day.","Rithwaan Khan","RK"),
                  ("Kal responded the same day I contacted him. He followed up with the ESA and completed the job in only 2 visits. The inspection passed the same day the job was completed. The price was also very fair.","Grace Onyeka","GO")],
    gallery_captions=["EV charger install, Mississauga","Light fixture adjustment","Electrical panel service","Residential rewiring"],
    primary="#1e3350", primary_dark="#13233a", accent="#4a90c4",
    hook="Your site is a single scrolling homepage with no dedicated page for your 155 five-star reviews, just a link out to Google. This version puts them front and center.",
    faqs=[("What areas do you serve?","We serve Mississauga, Oakville, Milton, and Brampton."),
          ("Are you available for emergencies?","Yes, Trust Electric Works offers 24/7 emergency electrical service."),
          ("Do you handle ESA inspections?","Yes, we provide same-day ESA inspections as part of our panel and rewiring work."),
          ("Is Trust Electric Works family-owned?","Yes, we're a family-owned electrical contractor serving the region.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkkea_EV7kC-zKx9BTSl3BvLqvPHmMzgJlRuqupCk1CY9OsldEC8h5KOd4VjKbhY-mH-SaX40uAV7igYsUC_rUSeic2bXSmTfQ9OvH272kIsZC3CnYWD0rfuth3b4bH2Z-wOl1XVg=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmMk076r8vDB4QTOJDaylGqbg0jPFGz6eNfmK49_O5yMHwR_f02SuVvOtpOH_3OPbtExkPKxLaYZAvnPdMkCS63Fn9aPEGgUScRtguplXi5FM2oDFdYmrEW2UA_Vh-nuUYMdPNjbw=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlGFJRTL2KWh50fjKpwyWOzYBwcOAipIcgzkyF_VBCqi05twFgwyC5hkkTNexvBwajbuc23gdoxrxxRR2b572pjs9K4Y5gEq6TYAy1eFDpodwQuSbWbXHDSQ9LQaVWCEw6y-ip3=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWltHA-Ip6xQoFtrG0xU9_TqWwRqJQlyhDUKdeyL41WkZF58DvRCHE3B2xCgmmASC4d-b7O6HwFoXSJIDzj0IUJSdo1xAuXVTO2XstKmSNFLwxtXrV4Xaz6kQaZEeP3njbi0OBXFNQ=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlukwcdyAltX159j0b60lexurRj-dXC-HaaeDkd3wBtHlaV6UvXibepHnUXgj8vgDwdS51SmN9hmB3l_uOYCTjUuSZBb4kXDF3rqsYacjnujmc01P1bAKKr1oGYGBXW5lG355a1QQ=w1920-h1080-k-no",
  ),
  dict(
    slug="crawford-electrical", name="Crawford Electrical Contracting Inc.", name_url="Crawford%20Electrical",
    city="Toronto", phone="416-910-1169", phone_tel="4169101169", wa_tel="14169101169",
    email="accounting@crawfordelectical.ca", rating="4.9", reviews="47", years="BBB", years_label="Accredited business",
    logo="CE",
    hero_headline="BBB-accredited. ESA low-risk rated. Trusted in Toronto.",
    tagline="Toronto electrical contractor carrying an ESA low-risk compliance rating and BBB accreditation, handling residential, commercial, and industrial work.",
    about="Crawford Electrical is a licensed Toronto contractor carrying an ESA low-risk compliance rating and BBB accreditation, working residential, commercial, and industrial jobs.",
    services=[("Residential Electrical","Panel upgrades, rewiring, and renovation electrical for homes."),
              ("Commercial Electrical","Electrical systems for offices, retail, and tenant fit-outs."),
              ("Industrial Electrical","Power distribution and equipment connections for facilities."),
              ("After-Hours Service","Available on request for urgent commercial and industrial needs."),
              ("EV Charger Installation","Certified installs for residential and commercial EV charging."),
              ("Generator Installation","Backup generator systems for homes and businesses.")],
    testimonials=[("Really happy with the work Trevor and his team completed in my century-old home. We needed to replace all of the knob-and-tube wiring and upgrade our panel. Each day the team cleaned up, which really showcases the care they bring. Would 100% recommend.","Mateusz Grobel","MG"),
                  ("Trevor and the team at Crawford are truly excellent. Responsive, reliable, professional and great customer service. Highly recommend.","Linda Christensen","LC"),
                  ("Electrician Eugene efficiently installed three light fixtures for us. He crawled around in the attic to fix the wiring, patient and skilled, professional, and a real problem solver. It's great to have an electrician you can trust.","Vivienne Bradbury","VB")],
    gallery_captions=["Knob-and-tube rewire, century home","Attic wiring for fixture install","Panel switch & city approval","Residential renovation electrical"],
    primary="#2a2f26", primary_dark="#1a1e17", accent="#c08a3e",
    hook="You're BBB-accredited and carry an ESA low-risk rating, real, verifiable trust signals, but they're buried on an About page most visitors never reach. This version puts them where people actually look first.",
    faqs=[("Are you BBB accredited?","Yes, Crawford Electrical carries BBB accreditation and an ESA low-risk compliance rating."),
          ("Do you install backup generators?","Yes, we install backup generator systems for both homes and businesses."),
          ("What types of properties do you work on?","We handle residential, commercial, and industrial electrical work across Toronto."),
          ("Do you offer after-hours service?","Yes, after-hours service is available on request for urgent commercial and industrial needs.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm7ud6OxYUQ7xzeYA1_Usn7rnKI8jcn1bzuofsJ4jziTnDr6AJYGbUYOIXESM9JDKheJyPfuYQnY2mGUploEps0racjXdclCO5ASNeyXaSd9jAliMhYbFPxQq23x2RCK9Bpx_un=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlJv5MPDRzOqsq2imFaZA5LtwjBNNO_3P6vpEeee5uM6qltaviUK-9anZN_7RsUpYT6s1nzmsSkZj3bl5fJH_OgEvYtVYKKDQ7Am-fA2LcN-T83dqVFNDEwmf7fvcH5tiKvWyat=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkLDybn0x95ztU8xpU_GGq0tMhiq12TOHgerBOJGAIEEeAdPDYxJrcFb7IM-nxSV1E0nmOhVqEsAreXb8FSQUhYA-lRiqrEg3q-8BoiBYICqv-JDZ9OOwQYFptpZspzuxR_j2chwA=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnKDfDEOcC0qguaxpbz9igHzmbDWjnUelsUx4uFL8lrH3pBfgSKS1mJXO7F6xRsSQYsFva7TGoTu7UStUXeRdGBQdTRONDmZThBhStQUm7QHz_9gVwgbmMm-3MuDG9KR6XvZ2CK=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlyvdLzcdHkvro21Xl8EuYE94xfvPXouNzStF3VcMT8SA3SFGMdMzDv1WEmkRCXXoBtcyhNP4Esf77P06wl0Jp5QpCxDI0W-q5ZYbAtpX-gtKK7Av_1Sdh759TwkS5bh_ansRm_=w1920-h1080-k-no",
  ),
  dict(
    slug="gibson-electrical", name="Gibson Electrical Contracting", name_url="Gibson%20Electrical",
    city="Mississauga", phone="647-994-2818", phone_tel="6479942818", wa_tel="16479942818",
    email="info@gibsonelectrical.com", rating="5.0", reviews="162", years="500+", years_label="Verified customers",
    logo="GE",
    hero_headline="500+ customers. A perfect 5.0. Personally, Edwin.",
    tagline="Mississauga and Toronto electrical contractor with a perfect 5.0 rating across 162 reviews, run personally by Edwin, who answers most calls himself.",
    about="Gibson Electrical Contracting has done residential and commercial electrical work across Mississauga and Toronto for over 500 verified customers, with Edwin personally handling most calls and most review replies.",
    services=[("Commercial Electrical","Design, installation, and maintenance for commercial spaces."),
              ("Panel Upgrades","Safe, code-compliant panel replacements and upgrades."),
              ("Residential Electrical","General repairs, upgrades, and installs for homes."),
              ("EV Charger Installation","Reliable EV charging setup for residential properties."),
              ("Safety Inspections & Repairs","Full outlet and wiring safety checks, hazard by hazard."),
              ("Outlet & GFI Service","Replacement and repair for outlets, GFIs, and receptacles.")],
    testimonials=[("If you are having any electrical issues please call Edwin. An outlet was making a sizzling sound and Edwin went out of his way to check it. It was a safety hazard. He checked all the outlets in the house and fixed the ones that needed immediate attention. I feel relieved and highly recommend him, without hesitation.","Kathleen M","KM"),
                  ("Excellent service from start to finish. When the electrical in our upstairs bathroom and bedrooms stopped working, Edwin quickly and methodically identified the issue. Multiple receptacles and a GFI outlet were replaced with great care. He clearly takes pride in his work.","Mike Vitez","MV"),
                  ("Edwin was easily reached later in the evening and attended to assess and repair our electrical panel. His friendly and courteous professionalism was a pleasure and the repair was done quickly and effectively.","It's Me X","IM")],
    gallery_captions=["Safety-hazard outlet inspection","GFI & receptacle replacement","Electrical panel repair","Whole-home outlet check"],
    primary="#2c2420", primary_dark="#1c1714", accent="#d97b3f",
    hook="Edwin replies to nearly every review personally, thanking people by name and inviting them to call again. That kind of follow-through doesn't show up anywhere on the current site, which is four service tiles and a contact button. This version gives it a home.",
    faqs=[("What areas do you serve?","We serve Mississauga and Toronto for residential and commercial electrical work."),
          ("Do you do safety inspections?","Yes, we provide full outlet and wiring safety checks, hazard by hazard."),
          ("Do you install EV chargers?","Yes, we provide reliable EV charging setup for residential properties."),
          ("Who will I be working with?","Edwin personally handles most calls and oversees the work himself.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlRWRJGGZe557BlubbYiZAl7K4QmpzwXQmlAb-YcLjYAJs4PXjpIj9VPlhh9mDyuUXrH9msDCaDdsqmaQFfnZVwGZ6V_Bzyy3Ngck39brKfSUZHXX8V16K4nfYz5XzfEKKyd3tA=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnCZaSk9HgLwyRBROzXodMnqly2jlvEBr5L4u8HVm1gDEviLdRSICsIIOi6X3acM1hZdxwZNMdj-X_U2vKm04nSkwwk-BENgXV3I3BOXn42EjRaPfiZviKcso_Lphy_B_0hUm98Q5twwg07=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWl2ohTc_Ufd4g4PsPzUw-qEa56K_Q0_jr0r6LqYYC6UNcoj7BNurj-HqoeSfTwqL9VPZE3YNUswmE5N5Bit95zLRf3JWGB1kje95LnxhIedcq5ONInuF_wOynnfYIxGd_QBmjGu21CT0XLr=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlXPE3ApfaaSKr_VGsDGb7FZGJW1IFuGzJbaTcV58maF73Y5_GdFATaNCwK9u-lnABXdbK54_dX0p6uXwVaBF3yDM5xXSWO4BwdhQ0pcG_jIcaiNRAJFDMf9t2SqIJPDIMOkvjt=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmwr_fHHrDe48WWggk0H_LycmtFhksEHgtcvJ90tgw9b827VUXIqC-w9ybZTNxVBNh1XUOnMzNwd1Bi738nPi2NKdaHh6oDQFCfbHx8m3MqupjGdp8ukzVW6nEP9n3e7cMZaRArEMLCmzBs=w1920-h1080-k-no",
  ),
  dict(
    slug="ss-electrical-appliances", name="SS Electrical and Appliances Inc.", name_url="SS%20Electrical%20and%20Appliances",
    city="Mississauga", phone="289-242-4498", phone_tel="2892424498", wa_tel="12892424498",
    email="info@sselectricalandappliances.ca", rating="5.0", reviews="92", years="5+", years_label="Years serving {{CITY}}",
    logo="SS",
    hero_headline="5.0 stars, 92 reviews, Mississauga's EV specialists.",
    tagline="Mississauga electrical and appliance contractor with a perfect 5.0 rating, known for clean EV charger installs and ESA-certified lighting work.",
    about="SS Electrical and Appliances has provided electrical and appliance services in Mississauga for 5+ years, from EV charger installs to full panel upgrades.",
    services=[("EV Charger Installation","Clean, code-compliant EV charger wiring, including Tesla setups."),
              ("Potlight Installation","Interior and exterior LED potlight installs."),
              ("Electrical Troubleshooting","Fast diagnosis for electrical system issues."),
              ("Code Compliance Upgrades","Bringing older electrical systems up to current code."),
              ("Appliance Installation & Repair","Installation and repair for major home appliances."),
              ("Commercial Electrical Repairs","Electrical repair and maintenance for commercial spaces.")],
    testimonials=[("I highly recommend SS Electrical and Appliances Inc.! They installed the electrical wiring for my Tesla charger, and the entire experience was outstanding. The team was incredibly polite, professional, honest, and respectful, and finished faster than I expected without compromising quality.","Reza Vafa","RV"),
                  ("Highly recommend these guys. Installed soffit lighting at my place a few weeks back, complete with ESA certificate. Fair price, on time, professional and cleaned up when the job was done.","Stephen Currado","SC"),
                  ("Great job on an EV Level 2 install and very reasonable, job was completed quickly and professionally, will recommend.","Cal Broderick","CB")],
    gallery_captions=["EV Level 2 charger install","Tesla charger wiring","Soffit lighting, ESA certified","Residential electrical service"],
    primary="#1a2e35", primary_dark="#101c20", accent="#39a884",
    hook="Your own site lists 300 reviews and 2,800 satisfied clients, numbers that don't line up with the 92 reviews on your actual Google profile. The real number is still a perfect 5.0. This version sticks to what's verifiable.",
    faqs=[("Do you install EV chargers, including Tesla?","Yes, including Tesla setups, all wired to code."),
          ("Do you provide ESA certification?","Yes, our lighting and electrical work comes with ESA certification where applicable."),
          ("Do you handle appliance repair too?","Yes, we install and repair major home appliances in addition to electrical work."),
          ("What areas do you serve?","We serve Mississauga and the surrounding area.")],
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQHJL3IFcZshQgGvc5tM02wu-pPxCmUsbBqjbfiVa_q6d_JtFHbq_Wv7qPK_ObyfJMlt7a_CxdmVJZ3tqy0i-XqhhS0mGomeoSih-ysqyKl1H-Rv1_DnAT1W5oZYIhyGnrj0ShPWJiIWoO=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmhY-Es1_PPFY0RhMq--gcPK0y103iygMKEy2Kbv-xnXKffV53pZ8vmV9Hlp7Yl3ChrPWnDZkXP45f-nHcRmQmWxvSZfzrq3E8ss7hqx-bx_88RgqKv9Dq3mvO3LX2EHpy-BGctVNcu_5Wz=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnff8niQe6N_ZIw16-aNHxyvFO9dl6sn0q_oE7gX3cKxB1K1yOT9PDRoxvKqmgZXltOim_ghFTJH_X5MeFHhotL7yo2hDNkXGh6bPOTmNK-hSUTjQGoSSyiwml9M4Z3_vM7t0AbwbpELBAr=w1920-h1080-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmtjUJKUeEMget__5uBTDDFKXNAMxZbBqOqmUTjrIYYIG5eY2cpG8m8MbfUlljwz2kIJr463ooQmSwEEX6AYcGqlGNjb9vxGkqjKRAXHfIEqKWojud_rgRaLYZW1dDrMGLRl46QDBEh65k=w1920-h1080-k-no"],
    hero_image="https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkD7xkS3o9D9vbcSLOoIJT_W00oxHl1QxRKFTPL2TvTcdCnDRsv0dgg3Zm-FsVkpwqp8oJrBtyCi1ujIHUj8VXX4TKfeDMbN6J3V4cl2q2XuHEsafRXZnyJMkihIXLqAslxCd5ulw=w1920-h1080-k-no",
  ),
]
