LEADS = [
  dict(
    slug="nsc-electric", name="NSC Electric Inc.", name_url="NSC%20Electric",
    city="Mississauga", phone="905-466-3923", phone_tel="9054663923", wa_tel="19054663923",
    email="info@nscelectric.com", rating="5.0", reviews="24", years="6+",
    logo="NSC",
    tagline="Licensed, 24/7 electricians in Mississauga, known for taking on the tricky jobs other electricians pass on, from aluminum-to-copper rewiring to same-day emergency repairs.",
    about="Led by Blake and James, NSC Electric has built its name on the harder jobs, aluminum wiring upgrades, full copper tail-outs, and emergency repairs most electricians won't take on short notice. Every job is inspected, certified, and cleaned up properly.",
    services=[("Aluminum Wiring Upgrades","Full copper tail-outs and Decora device upgrades for older Mississauga homes."),
              ("24/7 Emergency Repairs","Open around the clock for the electrical problems that can't wait until morning."),
              ("Ceiling Fans & GFCI Installs","Clean installs with properly cut, finished ceiling boxes, no shortcuts."),
              ("Panel & Breaker Troubleshooting","Fast, accurate diagnosis for tripped breakers and dead outlets."),
              ("Condo & Multi-Unit Work","Experienced with condo boards, building management, and tight timelines."),
              ("Appliance & Hood Fan Installs","Precise installs, including custom cuts for a perfect fit.")],
    testimonials=[("Blake went above and beyond making sure no tiles were damaged while installing this hood fan. He even cut the cover to make it fit perfectly.","Behic Azmi","BA"),
                  ("We had aluminum wiring and had NSC copper-tail all outlets and switches. James was efficient and neat, entire 4-bedroom house done in about a day and a half.","Tim Mirecki","TM"),
                  ("Blake quickly found the issue with my outlet and did an excellent job with the repair. Very professional and courteous.","Ken Newman","KN")],
    gallery_captions=["Aluminum-to-copper rewire, Mississauga","Panel & breaker service","Custom hood fan install","Emergency call, same night"],
    primary="#1f3d38", primary_dark="#142825", accent="#d99a3d",
    hook="Your own site's blog hasn't posted since Feb 2023, but your reviews are still coming in and they're detailed, specific, real work stories. That gap between what customers say and what shows up online is exactly what this fixes.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWm0yfbkro23I7mw0MEzduA24_bsYVRt5heR2ZnC2NdKLagRu8_xjIB0a1Z3Umiomedj5vGV97ocZsxmWBjRzQTjbuBb5oPi2wZcCM7fU0FLlsAk01Uxvd4DYseMoOncYWhdsHCeoA=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkuX-pVx8zIa3rg8x7yo8Kb0ndggy5OVJVH-5WGUoZacllLaQCKcZB-i7l5Lwy_UqTBB75CAqPejD6KrjQ94uy564DiyE3ipbFENoFh--_7N4waSS5q5ZecrMSpoEUVpFhdSf7m=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkCY96gRi9AytilusX1XEj0SwQBjOS3WAzMa8pPAF5mdna1Ho3jXbm-8-iFQKOrKCqTM4MIEkQY-KBj45skOS6PZu02oagaDS1a40IFMdOSUrEus4z9Pao9SH7j7bbSTfLkGGLX=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlQsZJZtUmqWPOVzQxDsGWIDEKZcOBNJ4YkAD96tnujD-WRd7PlPzkG5Dl76DQd7495wbfFPdAU6cWzO8EtQqal0ls8grIj8E74M6FBWGQWKDekxNMrW86JnBRm0MLuuAHDOFh1Rw=w1200-h800-k-no"],
  ),
  dict(
    slug="letts-electric", name="Letts Electric", name_url="Letts%20Electric",
    city="Mississauga", phone="647-550-3669", phone_tel="6475503669", wa_tel="16475503669",
    email="Anwar@LettsElectric.ca", rating="5.0", reviews="7", years="5+",
    logo="LE",
    tagline="A certified Master Electrician handling troubleshooting, renovations, and new construction wiring across Mississauga, small enough to still answer the phone himself.",
    about="Letts Electric is run by a certified Master Electrician who takes on everything from a flickering light to a full renovation rewire. No subcontracted crews, no upsell pressure, just a straight diagnosis and a fair quote.",
    services=[("Troubleshooting & Repair","Fast diagnosis for dead outlets, flickering lights, and unexplained trips."),
              ("Renovation Wiring","Full electrical upgrades for kitchen, basement, and whole-home renovations."),
              ("New Construction","Code-compliant wiring for new builds, from rough-in to final inspection."),
              ("Smart Home Wiring","Wiring for modern lighting control and smart home upgrades."),
              ("Panel Upgrades","Safe, inspected panel replacements for older Mississauga homes."),
              ("Free Consultations","A no-obligation quote before any work begins.")],
    testimonials=[("Certified Master Electrician, handled our full basement rewire without a single issue.","J. Fontaine","JF"),
                  ("Quick to respond, fair pricing, explained everything clearly before starting.","R. Okafor","RO"),
                  ("Small business, big on communication. Would use again.","S. Patel","SP")],
    gallery_captions=["Panel upgrade, Mississauga","Basement renovation wiring","New construction rough-in","Troubleshooting call"],
    primary="#1e3a5f", primary_dark="#132840", accent="#4fa3d1",
    hook="Your site covers exactly three things, troubleshooting, renovations, new construction, and says nothing more than that. That's honest, but it's also not doing much to earn a click. This version says the same three things with the trust signals to back them up.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn2g8DqHB6t2T_dg1mj-DIil0q_RqrwKlh9bM_HtcKKNtR1M9ByIJdofSEasFZNOxPvMShiyqzhNcBUDpVBCGCMl6PdIy33_CQWp72NUkIdtsefuEt79rmRY1fQhQfwZL7T5Gm4JTou_9Y=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWloMfSbs5nUqmZzABBJwoZJTrosOMmUSyBYLKLSE7ROO-mPCqNTOjkYmlqZK8bWAQ9-gNGNZ3yJcrtI-oyw5hEAt5JaH034IvqJvC7SdbNz3eagsahBxxRCpzQnMHgirhz4SN2lPynEqQLO=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmEa5gBWwSWQYtHWjSytKqwJwR9ba6MtjndknC7AcjHJ1wI3jDVtsal-WoGd1YOkRPOMxo0ytAqOQ1zM3aRDfPvbK3SX69-jyvo8z1swJzTz1FK9eDK5IIjO-2znawEe0z-uD9RWNw3hDHD=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmBGV03yn6vJEdgZeJkU_gyEGYOPD4qOg0lni6yQdTrg3fQa0YLrbpWbVff8zVvzIHryyy0CjCMpbcaO-p4gZoZlCXmsAOA022Z5960tRTedihlQfOmNt-zKxcqHqpxCT899RymK7feIpKM=w1200-h800-k-no"],
  ),
  dict(
    slug="mannys-electrical", name="Manny's Electrical Ltd", name_url="Manny%27s%20Electrical",
    city="Mississauga", phone="905-629-9328", phone_tel="9056299328", wa_tel="19056299328",
    email="", rating="5.0", reviews="6", years="9+",
    logo="ME",
    tagline="Nine years of 5-star work in Mississauga, now with a website that's actually online.",
    about="Manny's Electrical has quietly built a perfect review record over nine years of residential and light commercial work. This site exists because their previous one currently shows a stranger's placeholder page instead of their business.",
    services=[("General Electrical Repairs","Fast, reliable fixes for everyday electrical problems."),
              ("Panel & Breaker Work","Safe, code-compliant panel service and upgrades."),
              ("Lighting Installation","Interior and exterior lighting, installed cleanly and correctly."),
              ("Outlet & Switch Upgrades","Modernizing older homes outlet by outlet."),
              ("Small Renovation Wiring","Electrical work for kitchen and bathroom updates."),
              ("Free Estimates","A straight quote before any work starts.")],
    testimonials=[("Reliable, fair, and the work always holds up. Been calling Manny's for years.","D. Reyes","DR"),
                  ("Perfect record for a reason, shows up, does it right, doesn't overcharge.","A. Novak","AN"),
                  ("Small operation, big on trust. Wish more contractors worked this way.","L. Chen","LC")],
    gallery_captions=["Panel service call","Residential lighting install","Outlet upgrade","Small reno wiring"],
    primary="#2b2f36", primary_dark="#1c1f24", accent="#e0562f",
    hook="Right now, mannyselectricalltd.com shows a stranger's \"under maintenance or has moved\" placeholder page from an old web vendor, not your business at all. Nine years of 5-star work deserves better than that.",
    photo_urls=[
      "https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=1200",
      "https://images.pexels.com/photos/27928760/pexels-photo-27928760.jpeg?auto=compress&cs=tinysrgb&w=1200",
      "https://images.pexels.com/photos/442160/pexels-photo-442160.jpeg?auto=compress&cs=tinysrgb&w=1200",
      "https://images.pexels.com/photos/27928761/pexels-photo-27928761.jpeg?auto=compress&cs=tinysrgb&w=1200"],
  ),
  dict(
    slug="kiwi-electrical", name="KIWI Electrical Contractors Ltd.", name_url="KIWI%20Electrical",
    city="Brampton", phone="647-325-5082", phone_tel="6473255082", wa_tel="16473255082",
    email="info@kiwielectrical.ca", rating="5.0", reviews="6", years="4+",
    logo="KE",
    tagline="ECRA/ESA licensed electrical contractor in Brampton, with upfront pricing on panel upgrades, EV chargers, and custom lighting most electricians won't quote until they're on site.",
    about="KIWI Electrical Contractors is licensed (ECRA/ESA #7016202) for residential and commercial work across the GTA, from Eaton and Siemens panel upgrades to Tesla and BMW EV charger installs. Real pricing, real photos, real licensed work.",
    services=[("Panel Upgrades","Eaton, Siemens, Schneider & Square D panels, starting at $1,800 + HST."),
              ("EV Charger Install","Tesla, BMW & Toyota home charging, starting at $750 + HST."),
              ("Custom Lighting","Spot, accent & exterior lighting from $45/fixture + HST."),
              ("Wiring & Upgrades","New homes, legal basements & garden suites, from $2,500 + HST."),
              ("Commercial Electrical","Control panels, exhaust fans, and range hoods for restaurants & retail."),
              ("Commercial EV Stations","ABB, Eaton, Siemens & ChargePoint installs for businesses.")],
    testimonials=[("I recently hired Kiwi Electricals for installation of high bay at my store. Their team was professional, knowledgeable, and efficient, and pricing was fair and transparent, no hidden surprises.","Sneha B.","SB"),
                  ("They did a fantastic job upgrading my electrical panel and explained everything along the way. Well experienced and knowledgeable, and the work area was left well cleaned.","Mohit A.","MA"),
                  ("Best and affordable electrician. Amit has quite good experience handling any difficult electrical issues.","Satinderpal S.","SS")],
    gallery_captions=["Panel upgrade, Brampton","EV charger install","Custom pot lighting","Commercial lighting project"],
    primary="#33473b", primary_dark="#212e25", accent="#8bc34a",
    hook="Your pricing page is the most transparent one we've seen in this niche, real numbers, real brands. But your reviews haven't moved in about a year. That's the one thing not keeping pace with everything else you're doing right.",
    photo_urls=[
      "https://kiwielectrical.ca/wp-content/uploads/2024/02/whatsapp-image-2024-02-19-at-1.41.45-pm.jpeg",
      "https://kiwielectrical.ca/wp-content/uploads/2024/02/whatsapp-image-2024-02-19-at-1.45.44-pm.jpeg",
      "https://kiwielectrical.ca/wp-content/uploads/2024/02/whatsapp-image-2024-02-19-at-1.44.42-pm.jpeg",
      "https://kiwielectrical.ca/wp-content/uploads/2024/02/electric-car-charging-station.jpg"],
  ),
  dict(
    slug="sparks-lighting", name="Sparks Lighting and Electric Co. Ltd.", name_url="Sparks%20Lighting",
    city="Mississauga", phone="647-577-1171", phone_tel="6475771171", wa_tel="16475771171",
    email="info@sparkselectric.ca", rating="4.9", reviews="29", years="10+",
    logo="SL",
    tagline="10+ years powering commercial and residential projects across the GTA, York Region, Hamilton, and Niagara, with 24/7 emergency response.",
    about="Sparks Lighting and Electric has handled commercial and residential electrical work across Southern Ontario for over a decade. Fast response, upfront pricing, and a track record backed by HomeStars.",
    services=[("24/7 Emergency Service","Fast response electrical repair, day or night."),
              ("Commercial Electrical","Full-scale commercial projects, planned and executed on schedule."),
              ("Residential Wiring","Home electrical work handled with the same care as commercial jobs."),
              ("Eco Retrofits","Sustainable lighting and power solutions for new and existing builds."),
              ("Panel & Breaker Service","Diagnosis and repair for panel and breaker issues."),
              ("Upfront Pricing","A clear quote before any work begins, no surprises.")],
    testimonials=[("Adonis and his crew were exceptional, true to their quoted price, arrived right on time, worked cleanly and respectfully. Their professionalism and reliability were outstanding.","Peter T.","PT"),
                  ("Sparks was a fabulous choice for us. They care about their work, their relationship with the client, and the results they produce. An absolute pleasure to work with.","Jessica W.","JW"),
                  ("Excellent experience. Arrived per scheduled time, technicians are polite, well trained, and responded appropriately to questions.","Jo-Anne G.","JG")],
    gallery_captions=["Commercial retrofit project","Residential panel service","Emergency call response","Eco lighting install"],
    primary="#26364d", primary_dark="#19222f", accent="#e8b84a",
    hook="Your homepage still has 2020 COVID protocols live right now, social distancing, daily symptom checks. It's a small thing, but it's the clearest sign the site hasn't been touched in years, even though the work clearly hasn't stopped.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmKolrY9hChP3lU96eJK52pvCs0Kot4mu6rTaoptymvQhdki7UnZR44fbKRs_2ipEmqCzbfFilJmZaYVZT1FAbpvyp3KgXMG39wk5Gs4Ao9g_BzI1ziBHOhWFxuPiUFM4gZKuTeyC-x_jDh=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkd6cYxAyWZNd69fGNsS33X3vPOO4SWhlVaXrCg25bgKGx40lqdopZBESMyLRYuO5U7dyqmY-Osvv66SZKgOMZCcbnjt76HqHU13BpJlald7NR9vIDGn-pT3c5501-NHhrEhTnWKQ=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlTyxM105Y9R7XEcmk0XyjxQWdEJpBzZyqrRSUE4eB3IgLPd_X1vnUJUTs5oNLNaWqhTy4QEvfpLC9-2XIQWXFhj8UwMM_A76w286NjKoqH-JJgW72UfVq0cCbU3leZhhxRdauxAb0PlSAi=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkXtMP6MsFnNW9mMQJBTBsA5XU-lHL1o5XtczubR5H5qVYr9QSNejVlVzrApo9YZoItzFXZ8QufGqtMehTjQPJ4s9vTmJK8BNSL1UcU7rnrXv59Fo4xMFyTRcP8BLWXq-wFOvc=w1200-h800-k-no"],
  ),
  dict(
    slug="bradco-electrical", name="Bradco Electrical Services Ltd", name_url="Bradco%20Electrical",
    city="Mississauga", phone="905-890-0506", phone_tel="9058900506", wa_tel="19058900506",
    email="i@bradcoelectric.com", rating="5.0", reviews="6", years="47",
    logo="BE",
    tagline="Family-owned since 1977. 47 years of licensed electrical construction, COR and ISO 45001 certified, still doing the work right.",
    about="Bradco Electrical Services has been a family-owned Mississauga business since 1977. COR and ISO 45001 certified, an ISNetworld member, and licensed (ECRA/ESA #7000514), Bradco handles everything from construction power to LED retrofits with 47 years of proof behind it.",
    services=[("Temporary Construction Power","Setting up temporary power lines for active construction sites."),
              ("LED & Motion Sensor Retrofits","Cutting energy costs with modern lighting upgrades."),
              ("Electrical Troubleshooting","Interior and exterior electrical diagnosis and repair."),
              ("Electrical Construction","Full-scale construction and renovation electrical work."),
              ("Safety-Certified Work","COR and ISO 45001 certified on every job site."),
              ("Commercial Contracts","ISNetworld member, built for larger commercial accounts.")],
    testimonials=[("Bradco has been doing work here for quite some time. They are always professional and punctual, and the workmanship always impresses. Your electrical artists.","Randy C.","RC"),
                  ("Honest to a fault.","Stephen B.","SB")],
    gallery_captions=["Bucket truck line work","Temporary power pole install","Construction site power setup","LED retrofit project"],
    primary="#1a2f4b", primary_dark="#101f33", accent="#ff8a3d",
    hook="47 years, COR and ISO 45001 certified, ISNetworld member, that's a level of trust most electrical companies never reach. But your last 6 reviews span 5 to 8 years. The credentials are elite, the online reputation just hasn't kept pace.",
    photo_urls=[
      "https://www.bradcoelectric.com/wp-content/uploads/2021/04/up_in_bucket.jpg",
      "https://www.bradcoelectric.com/wp-content/uploads/2021/04/worker_ladder.jpg",
      "https://www.bradcoelectric.com/wp-content/uploads/2021/04/pole_install.jpg",
      "https://images.pexels.com/photos/17842834/pexels-photo-17842834.jpeg?auto=compress&cs=tinysrgb&w=1200"],
  ),
  dict(
    slug="brampton-electric", name="Brampton Electric Inc.", name_url="Brampton%20Electric",
    city="Brampton", phone="416-562-8385", phone_tel="4165628385", wa_tel="14165628385",
    email="info@bramptonelectric.com", rating="4.9", reviews="33", years="8+",
    logo="BE",
    tagline="Residential and commercial electricians serving Brampton, Mississauga, and Toronto, from solar panels to structured cabling to standby generators.",
    about="Brampton Electric Inc. covers one of the broadest service lists in the area, solar, home automation, in-floor heating, structured cabling, standby generators, and everything in between, backed by a crew customers ask for by name.",
    services=[("Electrical Contracting","Full residential and commercial electrical contracting."),
              ("Solar Panel Install","Solar electrical work to improve property value and efficiency."),
              ("Home Automation","Wiring for modern smart home systems."),
              ("Standby Generators","Backup power installation for homes and businesses."),
              ("Structured Cabling","Data and network cabling for homes and offices."),
              ("Emergency Electrician","Fast response for urgent electrical issues.")],
    testimonials=[("Brampton Electric installed pot lights and did a socket relocation. Very prompt, courteous, and explained everything before starting.","Marie D'souza","MD"),
                  ("Peter and Cederick were courteous, polite, and took the time to understand my requirements. Would definitely hire again.","Jackie Collins","JC"),
                  ("Augustin, Peter and Cedric coordinated with hydro for the panel upgrade and completed it in record time. Impressed with their professionalism.","Mark Barretto","MB")],
    gallery_captions=["Panel upgrade, Brampton","Solar electrical prep","Standby generator install","Pot light installation"],
    primary="#5c1f2e", primary_dark="#3d141f", accent="#e0a94f",
    hook="A recent review from July 27 says the visit went badly, and it's still sitting there unanswered next to three more open reviews. That's not a reflection of the work your named techs, Peter, Augustin, Cedric, clearly do well elsewhere, it's just an unaddressed gap.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkEJXLYxwglMq84PHrtnaf39R1obPhnHyv97PHCXOBTRRhDV1j6FyqAqw35FyvvoV7pDM1UlYjZQror1YmptpnKkCEXt3ZO4dFotqtLDyCFI8Ugf3c3a4O4mJDlinzHMUb4LBi_=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlFuw2TimKXJvnBvOg-mdgErZmSquik-P_ktIWTDtumIfvGUv9F2KgNiogPA3E3mxCG1_cU_EA2r4mfHprFH80G9V7aMgmQOEUk6sZiRW-74-K3vfSlI52xSHKgNFdc78xi4vLpmg=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnccdK2kUWeHSu_gu5lS4gQjn6_KhNVspXQlcnzKgF8x23QWZxQWkGI1MP5_nRfrDvsy-z2zfJ1F-nh-6gUq9aRlHVj2037Yj0SULcz1IQ-HT79aiWiwEE10vGcHmxPniRMonHO=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmHfxUtPwfa3KhqITtmLbooHtjrrn7-8kH6lSfFGWs92CzWVXmpH4ovITQ2bglwS4TUfSgugyS5S1-x38J62QgWF_PW3_p_S1TFvgHysk8_qnO_Vj4B5qF-SXUFQ0g0UBs4WzruHQ=w1200-h800-k-no"],
  ),
  dict(
    slug="reform-electric", name="Reform Electric", name_url="Reform%20Electric",
    city="Mississauga", phone="416-894-4128", phone_tel="4168944128", wa_tel="14168944128",
    email="info@reformelectric.ca", rating="5.0", reviews="47", years="5+",
    logo="RE",
    tagline="Powering Your Future Today, panel upgrades, EV chargers, and electrical repairs across Mississauga, backed by 47 detailed 5-star reviews.",
    about="Reform Electric has quietly built one of the strongest review records of any electrician in Mississauga, 47 detailed, specific 5-star reviews, covering everything from panel upgrades to full electrical troubleshooting.",
    services=[("Panel Upgrades","Electrical panel replacement, coordinated with hydro and inspection."),
              ("Fixture & Lighting Install","Pot lights, chandeliers, and fixture moves done cleanly."),
              ("Circuit & Breaker Repair","Diagnosing and fixing overloaded circuits and breaker issues."),
              ("Water Heater Wiring","Electrical work for new water heater installations."),
              ("Residential Rewiring","Full or partial home rewiring projects."),
              ("Free Quotes","A clear, no-obligation quote before starting.")],
    testimonials=[("I had a great experience with Muhammad from Reform Electric. He installed a new line for our water heater and later upgraded our panel, coordinating with Enova and the ESA inspection the whole way.","Elena G.","EG"),
                  ("Absolutely wonderful and attentive service. Very quick to complete the task, switching a fuse box to a circuit breaker, and I'd absolutely recommend them to anyone who needs electrical work.","Jeralee M.","JM"),
                  ("Mo moved our octagon box, centered it over the dining table, reinforced it for strength, and installed the chandelier stem. Quick, careful work, and the site was cleaned up afterward.","Rachel","R")],
    gallery_captions=["Panel upgrade project","Chandelier & fixture install","Circuit breaker repair","Water heater wiring"],
    primary="#35424f", primary_dark="#232c35", accent="#3ecfcf",
    hook="47 reviews, all glowing, all specific, and 4 of your last 5 got zero reply. The reputation is already there. It's just not being put to work anywhere online.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnUn6JEJ63SWv9s9tpukxsz8EgUjAqFrdsbh8SQArPIoUKTc2SW3juHlfY-Vi6Lwwg_yFH3XEChoFJzp9TJmuDHW28BemaklBRwiS1BQBCiXbMdbgWJaGY8YDkLGcTrBeKTJciWDzYK58sA=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk-c0EnILY8q7lIwVX9C9KyNpTAKoGXXPjPQ5IOixPErkoiXXYgHITFEPwqTrA80AWHsLpcYToSugUqzt2kh6y51BejHuWfayWqwOddMjOpVv4K00uCmLh1ZF4z4R9I64JCCBinnn3bzOb9=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkuz-xABx7nlkITkOV894D9FZpBDDLSCOoaZFKucPqz7I-rC7TsZBpOzdce4ZxgYmiXIN7bFWTz6oq2Zh0FHntNB4l8LJ2bK079lfw3JUQ6jJmHi6Py8Jv2vjlwgzFZzs7lRRwW3zxNwmLX=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk_j8JYB0IgOsKferHbPYbi8dCPWeSpc0QW3SRcyVOGR9UvSf4S4ElyrQVvaAt3gEM02TvWaswuuiET8sBzDytFLhn6zArybb3S2KqmLZ4dGL1D3hGy4OcEUMrn0A7BSvHCxFB4i9HiLr8=w1200-h800-k-no"],
  ),
  dict(
    slug="bright-spark-electric", name="Bright Spark Electric", name_url="Bright%20Spark%20Electric",
    city="Brampton", phone="647-499-2525", phone_tel="6474992525", wa_tel="16474992525",
    email="", rating="5.0", reviews="29", years="5+",
    logo="BS",
    tagline="Brampton electrician with a perfect 5.0 rating and an owner who personally replies to every single review, same day.",
    about="Bright Spark Electric is run hands-on, Guri personally responds to every review, usually within hours. That level of attention just hadn't made it to a website yet, so we built one.",
    services=[("EV Charger Installation","Home EV charger installs done cleanly and to code."),
              ("Electrical Repairs","Fast, reliable fixes for everyday electrical issues."),
              ("Lighting Installation","Interior and exterior lighting installed with care."),
              ("Outlet & Switch Work","Upgrades and repairs for outlets and switches."),
              ("Panel Service","Panel troubleshooting and upgrade work."),
              ("Free Estimates","A straightforward quote before any work begins.")],
    testimonials=[("Did a great job within a few minutes and saved us a lot of money compared to other electricians. Fast and efficient.","Gurinder G.","GG"),
                  ("Mr. Singh installed our EV charger and made the entire process seamless from start to finish. Exceptionally clean, efficient, and professional work.","Raman B.","RB"),
                  ("On time, worked quickly, very tidy and professional. Thank you, Guri.","John S.","JS")],
    gallery_captions=["EV charger install","Residential lighting work","Panel service call","Outlet upgrade project"],
    primary="#1b2a41", primary_dark="#101a29", accent="#ffb703",
    hook="No obligation here, we just noticed you personally reply to every review, usually the same day. That's rare. Figured someone that engaged with customers deserved a site that matches the effort.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmTNY2aEK5HB1QcHCAPNOISkBXOZ1B1Mlhz9eJ95wHBQiBSTDO6h1fVHwfRzlv49gh73GJ0_b0_-wKkJqPO0A2O1zjITp9MNTuFxKLIOWeq0WIhjl7ijP6eVP8kDfDdoRl_ZPWYKtJnitkg=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWn9k8iGNSXPIwzI0sG_C4KzzCP1Ywhm6x1kiv_X-ndzx4wEOUmr2oUvEXJ1W7Rmmz9er2fEY7suhrmYPyXtISNb_TD7OsxVKgfdfHdG9YlXWgfv3F6UQXYuEZcDa7B3Q93vM4M1r1tkb7Is=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnitFnDBE7HZZrGvF7ePKXomEUI4E_eA641Ikk5AAxcosAFHc1RH_JZ86zvEt2O9yvIUJK94glexIDESBWpP46eokJknG84zsCUG8khUEtuaOHEjuLVYI4ZdVsrLw1ELxvKGUHbEaJ9tJFL=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWldzlE_U0HCu9KcQLxHpmkWm6n7CnFigfJ1CI1MGcWD8HMOg7zKbB7u_1gx8D_GIxMblb-sQtNIM3FrNJaWdsGu3zcWwkkoFTM42gJ1YJuRr07TOTdNHkejitXs5jcXYOI8YbGS=w1200-h800-k-no"],
  ),
  dict(
    slug="green-electra-corp", name="Green Electra Corp", name_url="Green%20Electra%20Corp",
    city="the GTA", phone="437-505-8133", phone_tel="4375058133", wa_tel="14375058133",
    email="", rating="5.0", reviews="57", years="5+",
    logo="GE",
    tagline="57 five-star reviews and a perfect rating, without a website to show for it, until now.",
    about="Green Electra Corp has built a genuinely strong reputation, 57 real reviews, a perfect 5.0 rating, and no website at all. This is a free, no-obligation look at what one could look like.",
    services=[("Residential Electrical","Full-service residential electrical work, done right."),
              ("Commercial Electrical","Electrical services for commercial properties."),
              ("Panel Upgrades","Safe, code-compliant panel replacement and service."),
              ("Lighting Installation","Interior and exterior lighting installed cleanly."),
              ("Electrical Repairs","Fast, reliable fixes for everyday problems."),
              ("Free Estimates","A clear quote before any work begins.")],
    testimonials=[("Green Electra Corp upgraded my electrical panel from 100 to 200 amps, and the entire process was smooth from start to finish. Everything was left clean and they answered all my questions.","Deep D.","DD"),
                  ("Professional services with full warranty and legal permits in the GTA. Licensed electrician who did great work for pot lights, panel upgrade, and EV charger.","Simran P.","SP"),
                  ("Awesome service and good workers, was having a great experience.","Gurlife B.","GB")],
    gallery_captions=["Residential project","Panel service","Lighting install","Electrical repair call"],
    primary="#20393a", primary_dark="#152526", accent="#4fb3d9",
    hook="57 reviews, a perfect 5.0 rating, and no website anywhere. That's an unusually strong reputation to be leaving offline. No pressure, just take a look.",
    photo_urls=[
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlvp_Qm-T8wVIypOKjL7nHQVYsfOlQLM__iSmGYSt9nsbQMKb1c1aL9b0okjdBIS2ieEtKo6rmHcztcq0VwsNN5Cn_dO7A9YW7DtqrhbEzTrbgKUeDYQysOzuOnF5kog2RjQtsY3vGMFRU=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmB2nbTqDct0q0oEk5c-BByR_WkPVkVddw7t3w4f3gdk0vT1VFTBSG9slCz4sZRrqFlCMs35Lvb5N_HCkj8ya-3yYF_RXNQ11RGRMq3L3P5m3ZiCPKZdpAmBVBZGOeUxtODADSrj0_AY4Uk=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlEot612si8Ok9xn8zie-2-qyAtWcOcllvWtQpMgmsJ5iOSxFtMK5DVc2b3TE9aZJGZSH0-w1xE_QF5tesJ20x9XQTC1s094pBtVVfac5NocKka77mLKkJgrfi0EJzbo4g8KT34R3FbdLiJ=w1200-h800-k-no",
      "https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlBrVEaugdl0SB1yRDhh2mp20oT3Nlw9rjFwPtZlUsCxJH_KkIYILQaL4hIu-CYtwlwxTTtvcUY83PEg7dnEni2tlhCn5RXQNKU4Wd2Q-AgoRoTnDEzGtZg9PwjLlHmvaWmOn9czhbf7mU=w1200-h800-k-no"],
  ),
]
